SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO


CREATE VIEW [dbo].[CHCNWEB_SPECIALISTS_V1]
AS
SELECT DISTINCT TOP 100 PERCENT MIN(ID) AS Expr1, PROVID, CITY, CODE
FROM         dbo.CHCNWEB_SPECIALISTS
GROUP BY CITY, PROVID, CODE
ORDER BY MIN(ID)


GO
