SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO




--Updated with same code as Docustream changed by Candido (SK.2/18/2018)

CREATE VIEW [dbo].[CHCNAUTHREQ_CPT]
AS
--SELECT     COMMON_ID, LTRIM(RTRIM(SVCCODE)) AS PROCCODE, SVCDESC AS PROCDESC, PHCODE
--FROM         [EZCAP65TEST].[EZCAPDB].[DBO].[SERVICE_CODES_V]
--WHERE     CURRHIST = 'C' AND TODATE IS NULL AND PHCODE = 'H' AND LTRIM(RTRIM(SVCCODE)) IN
--                          (SELECT     LTRIM(RTRIM(SVCCODE))
--                            FROM          [EZCAP65TEST].[EZCAPDB].[DBO].[SERVICE_CODES_V]
--                            WHERE      PHCODE = 'P' AND CURRHIST = 'C' AND TODATE IS NULL)
--UNION ALL
--SELECT     COMMON_ID, LTRIM(RTRIM(SVCCODE)) AS PROCCODE, SVCDESC AS PROCDESC, PHCODE
--FROM         [EZCAP65TEST].[EZCAPDB].[DBO].[SERVICE_CODES_V]
--WHERE     CURRHIST = 'C' AND TODATE IS NULL AND PHCODE = 'P' AND LTRIM(RTRIM(SVCCODE)) NOT IN
--                          (SELECT     LTRIM(RTRIM(SVCCODE))
--                            FROM          [EZCAP65TEST].[EZCAPDB].[DBO].[SERVICE_CODES_V]
--                            WHERE      PHCODE = 'H' AND CURRHIST = 'C' AND TODATE IS NULL)

SELECT     S.COMMON_ID, LTRIM(RTRIM(S.SVCCODE)) AS PROCCODE, S.SVCDESC AS PROCDESC, PHCODE
FROM         [EZCAP65TEST].[EZCAPDB].[DBO].[SERVICE_CODES_V] S JOIN EZCAP65TEST.EZCAPDB.dbo._CHCN_REV_CODES R ON LTRIM(RTRIM(S.SVCCODE))=R.CODE
--[EZCAP65TEST].[EZCAPDB].[dbo].[_AAH_UM_REVCODES] R ON LTRIM(RTRIM(SVCCODE))=R.REVCODE
WHERE     CURRHIST = 'C' AND TODATE IS NULL AND PHCODE = 'H' AND LTRIM(RTRIM(SVCCODE)) IN
                          (SELECT     LTRIM(RTRIM(SVCCODE))
                            FROM          [EZCAP65TEST].[EZCAPDB].[DBO].[SERVICE_CODES_V]
                            WHERE      PHCODE = 'P' AND CURRHIST = 'C' AND TODATE IS NULL)
UNION ALL
-- UPDATED TO EXCLUDE REV CODES ALLREADY SELECTED ABOVE AND NOT EXCLUDE FROM H TYPE VALUES, CTA, 02/08/2018
SELECT     COMMON_ID, LTRIM(RTRIM(SVCCODE)) AS PROCCODE, SVCDESC AS PROCDESC, PHCODE
FROM         [EZCAP65TEST].[EZCAPDB].[DBO].[SERVICE_CODES_V]
WHERE     CURRHIST = 'C' AND TODATE IS NULL AND PHCODE = 'P' AND LTRIM(RTRIM(SVCCODE)) NOT IN
                          (SELECT     LTRIM(RTRIM(CODE))
                            FROM   EZCAP65TEST.EZCAPDB.dbo._CHCN_REV_CODES )      --[EZCAP65TEST].[EZCAPDB].[DBO].[SERVICE_CODES_V]
                            --WHERE      PHCODE = 'H' AND CURRHIST = 'C' AND TODATE IS NULL)




GO
