SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO





CREATE VIEW [dbo].[REQUESTING_PROV]
AS
SELECT     PV.PROV_KEYID, VM.VENDORNM, PV. VENDOR, PC.REV_FULLNAME, PC.PROVID, PC.LASTNAME
FROM         [EZCAP65TEST].[EZCAPDB].[DBO].[PROV_VENDINFO_V] PV JOIN
                      [EZCAP65TEST].[EZCAPDB].[DBO].[PROV_COMPANY_V] PC ON PV.PROV_KEYID = PC.PROV_KEYID JOIN
                      [EZCAP65TEST].[EZCAPDB].[DBO].[VEND_MASTERS_V] VM ON PV. VENDOR = VM.VENDORID
WHERE     PV.TYPE <> 'TERMINATED' AND NULLIF (PC.FIRSTNAME, '') IS NOT NULL
UNION ALL
SELECT     PV.PROV_KEYID, VM.VENDORNM, PV. VENDOR, PC.REV_FULLNAME, PC.PROVID, PC.LASTNAME
FROM         [EZCAP65TEST].[EZCAPDB].[DBO].[PROV_VENDINFO_V] PV JOIN
                      [EZCAP65TEST].[EZCAPDB].[DBO].[PROV_COMPANY_V] PC ON PV.PROV_KEYID = PC.PROV_KEYID JOIN
                      [EZCAP65TEST].[EZCAPDB].[DBO].[VEND_MASTERS_V] VM ON PV. VENDOR = VM.VENDORID
WHERE     PV.TYPE <> 'TERMINATED' AND NULLIF (PC.FIRSTNAME, '') IS NULL





GO
