SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO


CREATE VIEW [dbo].[CHCNAUTH_FACT_V]
AS
SELECT        g.AUTH_GRID_ID, c.CODES_ID, r.RESTRICTIONS_ID, g.SVC_CODE, g.CATEGORY, g.SUB_CATEGORY, c.SVCDESC, g.IS_DUP, g.GRID_DETERM, r.HEALTHPLAN, 
                         r.COVERAGE, r.PROVID, r.PLACESVC, r.REST_DETERM, r.EFFECTIVE_DATE, r.TERM_DATE
FROM            dbo.CHCNAUTH_GRID AS g LEFT OUTER JOIN
                         dbo.CHCNAUTH_CODES AS c ON g.SVC_CODE = c.SVCCODE LEFT OUTER JOIN
                         dbo.CHCNAUTH_RESTRICTIONS AS r ON g.SVC_CODE = r.SVCCODE


GO
