SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO




CREATE VIEW [dbo].[CHCNPORTAL_REFPROCCODES_VS]
AS
SELECT     COMMON_ID, PHCODE, UPPER(LTRIM(RTRIM(SVCCODE))) AS PROCCODE, UPPER(SVCDESC) AS PROCDESC
FROM         EZCAP65TEST.EZCAPDB.dbo.SERVICE_CODES_VS AS SERVICE_CODES_VS_1
WHERE     (PHCODE = 'P') AND (CURRHIST = 'C')




GO
