SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO




CREATE VIEW [dbo].[CHCNWEB_SPECIALISTS_ALL_VS]
AS
SELECT DISTINCT 
                      dbo.CHCNWEB_SPECIALISTS_ALL.ID, dbo.CHCNWEB_SPECIALISTS_ALL.PROVID, dbo.CHCNWEB_SPECIALISTS_ALL.LASTNAME, 
                      dbo.CHCNWEB_SPECIALISTS_ALL.FIRSTNAME, dbo.CHCNWEB_SPECIALISTS_ALL.STREET, dbo.CHCNWEB_SPECIALISTS_ALL.CITY, 
                      dbo.CHCNWEB_SPECIALISTS_ALL.ZIP, dbo.CHCNWEB_SPECIALISTS_ALL.PHONE, dbo.CHCNWEB_SPECIALISTS_ALL.FAX, 
                      dbo.CHCNWEB_SPECIALISTS_ALL.MEMOLINE3, dbo.CHCNWEB_SPECIALISTS_ALL.MEDICAL_GROUP, dbo.CHCNWEB_SPECIALISTS_ALL.CODE, dbo.CHCNWEB_SPECIALISTS_ALL.CONTRACT
FROM         dbo.CHCNWEB_SPECIALISTS_ALL INNER JOIN
                      dbo.CHCNWEB_SPECIALISTS_ALL_V ON dbo.CHCNWEB_SPECIALISTS_ALL.ID = dbo.CHCNWEB_SPECIALISTS_ALL_V.ID



GO
