SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO



CREATE VIEW [dbo].[CHCNPORTAL_MEMBERS_VS]
AS
SELECT     MEMB_KEYID, MEMB_MPI_NO, MEMBID, MEMBSSN, SUBSSN, PATID, RLSHIP, STATUS, LASTNM, FIRSTNM, REV_FULLNAME, SEX, BIRTH, 
                      MARITAL, WORKPHONE, EXTENSION, FAX, EMAIL, LANGUAGE, ETHNICITY, STREET, STREET2, CITY, ZIP, PHONE, OTHCOV, OTHPRIM, OTHNAME, 
                      MEMOLINE1, MEMOLINE2, MEMOLINE3, MEMOLINE4, PCP, PCPFROMDT, PCPTHRUDT, TRANDATE, OPFROMDT, OPTHRUDT, HPFROMDT, HPCODE, 
                      OPT, HMO, HP, CHC, CREATEDATE, SITE, USERFIELD1, USERFIELD2, HFPCOPAY
FROM         EZCAP65TEST.EZCAPDB.dbo.CHCNWEB_MEMBMASTER_VS AS CHCNWEB_MEMBMASTER_VS_1



GO
