SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO


/* Get last EOB with NO CHECK with Vendor ID


*/
CREATE VIEW [dbo].[CHCNWEB_EOB_MAX]
AS
SELECT DISTINCT VENDORID, MAX(DATEPAID) AS DATEPAID
FROM         dbo.CHCNWEB_EOB
GROUP BY VENDORID
HAVING      (MAX(DATEPAID) = DATEADD(d, - 1, CONVERT(char(10), GETDATE(), 101)))


GO
