SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO


-- Updated to use static table CHCNPORTAL_MEMB_MASTER, CTA<  03/11/2014
CREATE PROCEDURE [dbo].[CHCNPortal_GetMemberDetail]

@MembKeyid varchar(max)

as

If @MembKeyid IS NULL 
	BEGIN
	RETURN
	END
ELSE
BEGIN
SELECT     REV_FULLNAME, SEX, CONVERT(char(10),BIRTH,101) AS DOB, MEMBID, PATID, 
           CONVERT(char(10),OPFROMDT,101) AS EFFDT, CONVERT(char(10),OPTHRUDT,101) AS TERMDT, 
		   STATUS, PCP, LEFT(OPT, LEN(OPT) - 3) AS OPTNAME, CLINIC, MEMOLINE1, MEMOLINE2, MEMOLINE3,MEMOLINE4,
		USERFIELD1, USERFIELD2, [LANGUAGE], NOTES, STREET, STREET2, CITY, ZIP, PHONE,
		OPTDESC -- ADDED PER JIRA PRIOR-928 TICKET, CTA,03/13/2017 
FROM    dbo.CHCNPORTAL_MEMB_MASTER     --[EZCAPDB2].[EZCAPDB].[dbo].CHCNPORTAL_MEMBMASTER_VS
WHERE  (CAST(Memb_KeyID as varchar(max)) = @MembKeyid) 

END



GO
