SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO








CREATE PROCEDURE [dbo].[CHCNPortal3_GetAuthsByAdvancedSearch]

-- Updated for Alameda Alliance and Anthem BC user filtering, CTA, 06/28/2016 
-- Updated to display messaging flags SK.11/10/2016
-- Added EXPIRED SK.5/12/2017
-- Added to filter auth status in ('O','Q') SK.9/26/2017
-- Added 'Paritally Approved' status SK.2/13/2018


@COMPANYIDLIST VARCHAR(150),
@LASTNM VARCHAR(20),
@FIRSTNM VARCHAR(10),
@DOB DATETIME,
@PATID VARCHAR(12),
@MEMBID VARCHAR(11),
@AUTHNO VARCHAR(25),
@PROVLN VARCHAR(20),
@REQUESTID VARCHAR(25)

AS 

IF @LASTNM IS NULL AND @FIRSTNM IS NULL AND @DOB IS NULL AND @PATID IS NULL AND @MEMBID IS NULL AND @AUTHNO IS NULL AND @PROVLN IS NULL AND @REQUESTID IS NULL
	RETURN
ELSE
BEGIN
	SET @CompanyIDList = REPLACE(@CompanyIDList,'-','') --SK.05/12/2016
	-- START ALAMEDA AND ANTHEM FILTERING
	IF @COMPANYIDLIST LIKE '%ALAMEDA%' 
		BEGIN
			SELECT 	DISTINCT TOP 101 M.AUTHNO, 
					CONVERT(char(10),M.REQDATE, 101) As Submit_Date,
					Modified = CASE WHEN (SELECT COUNT(*) FROM [EZCAP65TEST].EZCAPDB.DBO.CSM_MASTERS_V 
								WHERE INCTYPE = 'MOD' AND CUSTCATEGORY = 'PROVIDER' AND  REFCATEGORY ='AUTHORIZATION' AND STATUS = 'O'
								AND REFAUTHNO = M.AUTHNO)>0 THEN 'Yes' ELSE 'No' END,	
					M.MEMBNAME, CONVERT(char(10),M.BIRTH,101) As DateOfBirth,
								STATUS = 	CASE WHEN M.[Status] = 'APPROVED' THEN 'APPROVED'
								WHEN M.[STATUS] = 'FUTURE ELECTIVE (APPROVED)' THEN 'APPROVED FUTURE ELECTIVE'
								WHEN M.[STATUS] = 'DEFERRED (FOR UM INFO)' THEN 'DEFERRED' 
								WHEN M.[STATUS] = 'PARTIALLY APPROVED' THEN 'PARTIALLY APPROVED' 
								WHEN M.[STATUS] not in ('CCS REFERRED', 'DENIED', 'CANCELLED','CCS APPROVED','EXPIRED') THEN 'SUBMITTED' 
								ELSE M.[STATUS] END,
					M.OnsetDT as DecisionDate, 
					AttachmentCount = (SELECT COUNT(*) FROM [EZCAP65TEST].[EZCAPDB].[DBO].[CHCNEDI_AUTHIMAGES_VS] AS ATT WITH (NOLOCK) 
													INNER JOIN [EZCAP65TEST].[EZCAPDB].[DBO].[AUTH_MASTERS_V] AM WITH (NOLOCK) ON ATT.AUTHNO = AM.AUTHNO
								WHERE ATT.AUTHNO=M.AUTHNO AND ((ATT.ReferenceID IN ('DENIAL LETTER') AND AM.STATUS = '3')
															OR (ATT.ReferenceID IN ('DEFERRED LETTER') AND AM.STATUS = '9')
															OR (ATT.ReferenceID LIKE '%RECLASSIFICATION NOTICE%')
															OR (ATT.Description = 'APPROVAL LETTER' AND AM.STATUS LIKE '[1PV]'))),
					M.AUTHDATE,
					M.SPECCODE, MBeta.UserID,lm.IsRead,lm.LastMsgReadDt
			FROM	[EZCAP65TEST].[EZCAPDB].[dbo].[CHCNPORTAL_AUTHMASTER_VS] as M LEFT JOIN CHCNAuthReq_Master MBeta ON M.AUTHNO=MBeta.EZCAP_AuthNo
				LEFT JOIN (SELECT AuthNo, MAX(ReadDate) AS LastMsgReadDt, MIN(CAST(IsRead AS INT)) AS IsRead FROM CHCNPORTAL3_MESSAGE_LOG GROUP BY AuthNo) lm ON M.AUTHNO = lm.AuthNo 
			WHERE --(M.OPT LIKE 'AA%') AND
				(SUBSTRING(M.OPT, 1, 4) IN ('AADS', 'AAGC', 'AAML', 'AAMM', 'AAMX')) AND
				((M.LASTNM = @LASTNM) or (M.LASTNM LIKE @LASTNM + '%') or (@LASTNM IS NULL)) and	
				((M.FIRSTNM = @FIRSTNM) or (M.FIRSTNM LIKE @FIRSTNM + '%') or (@FIRSTNM IS NULL)) and	
				(((M.AAH_ID = @Patid) or (M.AAH_ID  LIKE '%'+@Patid + '%') or (@PATID IS NULL)) OR
				((M.AAHS_ID = @Patid) or (M.AAHS_ID  LIKE '%'+@Patid + '%') or (@PATID IS NULL)) OR
				((M.AACC_ID = @Patid) or (M.AACC_ID  LIKE '%'+@Patid + '%') or (@PATID IS NULL)) OR
				((M.ANTHEM_ID = @Patid) or (M.ANTHEM_ID  LIKE '%'+@Patid + '%') or (@PATID IS NULL)) OR
				((M.HN_ID = @Patid) or (M.HN_ID  LIKE '%'+@Patid + '%') or (@PATID IS NULL)))and
				((M.MEMBID = @MEMBID) or (M.MEMBID LIKE @MEMBID + '%') or (@MEMBID IS NULL)) and
				((M.BIRTH = @DOB) or (@DOB IS NULL)) AND
				((M.AUTHNO = @AUTHNO) or (M.AUTHNO like @AUTHNO + '%') or (@AUTHNO IS NULL)) AND
				((M.PROVNAME = @PROVLN) or (M.PROVNAME LIKE @PROVLN + '%') or (@PROVLN IS NULL)) AND
				((M.REQUESTID = @REQUESTID) or (M.REQUESTID LIKE @REQUESTID + '%') or (@REQUESTID IS NULL))
				AND M.STATUSCODE NOT IN ('O','Q')
			ORDER BY M.authno desc
		END

	ELSE IF @COMPANYIDLIST LIKE '%ANTHEM%' 
		BEGIN	
			SELECT 	DISTINCT TOP 101 M.AUTHNO, 
					CONVERT(char(10),M.REQDATE, 101) As Submit_Date,
					Modified = CASE WHEN (SELECT COUNT(*) FROM [EZCAP65TEST].EZCAPDB.DBO.CSM_MASTERS_V 
								WHERE INCTYPE = 'MOD' AND CUSTCATEGORY = 'PROVIDER' AND  REFCATEGORY ='AUTHORIZATION' AND STATUS = 'O'
								AND REFAUTHNO = M.AUTHNO)>0 THEN 'Yes' ELSE 'No' END,	
					M.MEMBNAME, CONVERT(char(10),M.BIRTH,101) As DateOfBirth,
								STATUS = 	CASE WHEN M.[Status] = 'APPROVED' THEN 'APPROVED'
								WHEN M.[STATUS] = 'FUTURE ELECTIVE (APPROVED)' THEN 'APPROVED FUTURE ELECTIVE'
								WHEN M.[STATUS] = 'DEFERRED (FOR UM INFO)' THEN 'DEFERRED' 
								WHEN M.[STATUS] = 'PARTIALLY APPROVED' THEN 'PARTIALLY APPROVED' 
								WHEN M.[STATUS] not in ('CCS REFERRED', 'DENIED', 'CANCELLED','CCS APPROVED','EXPIRED') THEN 'SUBMITTED' 
								ELSE M.[STATUS] END,
					M.OnsetDT as DecisionDate, 
					--AttachmentCount = (	SELECT Count(*) FROM [EZCAP65TEST].[EZCAPDB].[DBO].[CHCNEDI_AUTHIMAGES_VS] as ATT 
					--					WHERE ATT.AUTHNO=M.AUTHNO),
					AttachmentCount = (SELECT COUNT(*) FROM [EZCAP65TEST].[EZCAPDB].[DBO].[CHCNEDI_AUTHIMAGES_VS] AS ATT WITH (NOLOCK) 
													INNER JOIN [EZCAP65TEST].[EZCAPDB].[DBO].[AUTH_MASTERS_V] AM WITH (NOLOCK) ON ATT.AUTHNO = AM.AUTHNO
								WHERE ATT.AUTHNO=M.AUTHNO AND ((ATT.ReferenceID IN ('DENIAL LETTER') AND AM.STATUS = '3')
															OR (ATT.ReferenceID IN ('DEFERRED LETTER') AND AM.STATUS = '9')
															OR (ATT.ReferenceID LIKE '%RECLASSIFICATION NOTICE%')
															OR (ATT.Description = 'APPROVAL LETTER' AND AM.STATUS LIKE '[1PV]'))),
					M.AUTHDATE,
					M.SPECCODE, MBeta.UserID,lm.IsRead,lm.LastMsgReadDt
			FROM	[EZCAP65TEST].[EZCAPDB].[dbo].[CHCNPORTAL_AUTHMASTER_VS] as M LEFT JOIN CHCNAuthReq_Master MBeta ON M.AUTHNO=MBeta.EZCAP_AuthNo
				LEFT JOIN (SELECT AuthNo, MAX(ReadDate) AS LastMsgReadDt, MIN(CAST(IsRead AS INT)) AS IsRead FROM CHCNPORTAL3_MESSAGE_LOG GROUP BY AuthNo) lm ON M.AUTHNO = lm.AuthNo 
			WHERE (M.OPT LIKE 'BC%') AND
				((M.LASTNM = @LASTNM) or (M.LASTNM LIKE @LASTNM + '%') or (@LASTNM IS NULL)) and	
				((M.FIRSTNM = @FIRSTNM) or (M.FIRSTNM LIKE @FIRSTNM + '%') or (@FIRSTNM IS NULL)) and	
				(((M.AAH_ID = @Patid) or (M.AAH_ID  LIKE '%'+@Patid + '%') or (@PATID IS NULL)) OR
				((M.AAHS_ID = @Patid) or (M.AAHS_ID  LIKE '%'+@Patid + '%') or (@PATID IS NULL)) OR
				((M.AACC_ID = @Patid) or (M.AACC_ID  LIKE '%'+@Patid + '%') or (@PATID IS NULL)) OR
				((M.ANTHEM_ID = @Patid) or (M.ANTHEM_ID  LIKE '%'+@Patid + '%') or (@PATID IS NULL)) OR
				((M.HN_ID = @Patid) or (M.HN_ID  LIKE '%'+@Patid + '%') or (@PATID IS NULL)))and
				((M.MEMBID = @MEMBID) or (M.MEMBID LIKE @MEMBID + '%') or (@MEMBID IS NULL)) and
				((M.BIRTH = @DOB) or (@DOB IS NULL)) AND
				((M.AUTHNO = @AUTHNO) or (M.AUTHNO like @AUTHNO + '%') or (@AUTHNO IS NULL)) AND
				((M.PROVNAME = @PROVLN) or (M.PROVNAME LIKE @PROVLN + '%') or (@PROVLN IS NULL)) AND
				((M.REQUESTID = @REQUESTID) or (M.REQUESTID LIKE @REQUESTID + '%') or (@REQUESTID IS NULL))
				AND M.STATUSCODE NOT IN ('O','Q')
			ORDER BY M.authno desc
		END
	-- END OF ALAMEDA AND ANTHEM FILTERING	
	ELSE
		BEGIN	
			SELECT 	DISTINCT TOP 101 M.AUTHNO, 
					CONVERT(CHAR(10),M.REQDATE, 101) AS Submit_Date,
					--Modified = CASE WHEN (SELECT count(*) FROM [EZCAP65TEST].EZCAPDB.DBO.CSM_MASTERS_V 
					--			WHERE INCTYPE = 'MOD' AND CUSTCATEGORY = 'PROVIDER' AND  REFCATEGORY ='AUTHORIZATION'
					--			AND REFAUTHNO = AUTHNO)>0 Then 'Yes' 
					--			WHEN (SELECT COUNT(*) FROM  [EZCAP65TEST].[EZCAPDB].[DBO].[AUTH_NOTES_V] WHERE AUTHNO = M.AUTHNO AND SUBJECT ='MOD') > 0 THEN 'Yes' ELSE 'No' End,
					--Updated to include the active modification requests in Customer Service only (SK 9/23/2015)
					Modified = CASE WHEN (SELECT COUNT(*) FROM [EZCAP65TEST].EZCAPDB.DBO.CSM_MASTERS_V 
								WHERE INCTYPE = 'MOD' AND CUSTCATEGORY = 'PROVIDER' AND  REFCATEGORY ='AUTHORIZATION' AND STATUS = 'O'
								AND REFAUTHNO = M.AUTHNO)>0 THEN 'Yes' ELSE 'No' END,	
					M.MEMBNAME, CONVERT(CHAR(10),M.BIRTH,101) AS DateOfBirth,
								STATUS = 	CASE WHEN M.[Status] = 'APPROVED' THEN 'APPROVED'
								WHEN M.[STATUS] = 'FUTURE ELECTIVE (APPROVED)' THEN 'APPROVED FUTURE ELECTIVE'
								WHEN M.[STATUS] = 'DEFERRED (FOR UM INFO)' THEN 'DEFERRED' 
								WHEN M.[STATUS] = 'PARTIALLY APPROVED' THEN 'PARTIALLY APPROVED' 
								WHEN M.[STATUS] NOT IN ('CCS REFERRED', 'DENIED', 'CANCELLED','CCS APPROVED','EXPIRED') THEN 'SUBMITTED' 
								ELSE M.[STATUS] END,
					M.OnsetDT AS DecisionDate, 
					--AttachmentCount = (	SELECT COUNT(*) FROM [EZCAP65TEST].[EZCAPDB].[DBO].[CHCNEDI_AUTHIMAGES_VS] AS ATT 
					--					WHERE ATT.AUTHNO=M.AUTHNO),
					AttachmentCount = (SELECT COUNT(*) FROM [EZCAP65TEST].[EZCAPDB].[DBO].[CHCNEDI_AUTHIMAGES_VS] AS ATT WITH (NOLOCK) 
													INNER JOIN [EZCAP65TEST].[EZCAPDB].[DBO].[AUTH_MASTERS_V] AM WITH (NOLOCK) ON ATT.AUTHNO = AM.AUTHNO
								WHERE ATT.AUTHNO=M.AUTHNO AND ((ATT.ReferenceID IN ('DENIAL LETTER') AND AM.STATUS = '3')
															OR (ATT.ReferenceID IN ('DEFERRED LETTER') AND AM.STATUS = '9')
															OR (ATT.ReferenceID LIKE '%RECLASSIFICATION NOTICE%')
															OR (ATT.Description = 'APPROVAL LETTER' AND AM.STATUS LIKE '[1PV]'))),
					M.AUTHDATE,
					M.SPECCODE, MBeta.UserID,lm.IsRead,lm.LastMsgReadDt
			FROM	[EZCAP65TEST].[EZCAPDB].[dbo].[CHCNPORTAL_AUTHMASTER_VS] AS M LEFT JOIN CHCNAuthReq_Master MBeta ON M.AUTHNO=MBeta.EZCAP_AuthNo
				LEFT JOIN (SELECT AuthNo, MAX(ReadDate) AS LastMsgReadDt, MIN(CAST(IsRead AS INT)) AS IsRead FROM CHCNPORTAL3_MESSAGE_LOG GROUP BY AuthNo) lm ON M.AUTHNO = lm.AuthNo 
			--WHERE (	CHARINDEX(M.COMPANY_ID,@CompanyIDList)>0 or 
			--		CHARINDEX(M.RQPROVID, @CompanyIDList)>0 or 
			--		CHARINDEX(M.RENDPROVID, @CompanyIDList)>0 or 
			--		CHARINDEX(M.CLINIC, @CompanyIDList)>0 or 
			--		CHARINDEX(M.FACILITYID, @CompanyIDList)>0) AND
			--SK.05/12/2016
			WHERE (	CHARINDEX(M.COMPANY_ID,@CompanyIDList)>0 OR 
					CHARINDEX(REPLACE(M.RQPROVID,'-',''), @CompanyIDList)>0 OR 
					CHARINDEX(REPLACE(M.RENDPROVID,'-',''), @CompanyIDList)>0 OR 
					CHARINDEX(REPLACE(M.CLINIC,'-',''), @CompanyIDList)>0 OR 
					CHARINDEX(REPLACE(M.FACILITYID,'-',''), @CompanyIDList)>0) AND
				((M.LASTNM = @LASTNM) OR (M.LASTNM LIKE @LASTNM + '%') OR (@LASTNM IS NULL)) AND	
				((M.FIRSTNM = @FIRSTNM) OR (M.FIRSTNM LIKE @FIRSTNM + '%') OR (@FIRSTNM IS NULL)) AND	
				(((M.AAH_ID = @Patid) OR (M.AAH_ID  LIKE '%'+@Patid + '%') OR (@PATID IS NULL)) OR
				((M.AAHS_ID = @Patid) OR (M.AAHS_ID  LIKE '%'+@Patid + '%') OR (@PATID IS NULL)) OR
				((M.AACC_ID = @Patid) OR (M.AACC_ID  LIKE '%'+@Patid + '%') OR (@PATID IS NULL)) OR
				((M.ANTHEM_ID = @Patid) OR (M.ANTHEM_ID  LIKE '%'+@Patid + '%') OR (@PATID IS NULL)) OR
				((M.HN_ID = @Patid) OR (M.HN_ID  LIKE '%'+@Patid + '%') OR (@PATID IS NULL)))AND
				((M.MEMBID = @MEMBID) OR (M.MEMBID LIKE @MEMBID + '%') OR (@MEMBID IS NULL)) AND
				((M.BIRTH = @DOB) OR (@DOB IS NULL)) AND
				((M.AUTHNO = @AUTHNO) OR (M.AUTHNO LIKE @AUTHNO + '%') OR (@AUTHNO IS NULL)) AND
				((M.PROVNAME = @PROVLN) OR (M.PROVNAME LIKE @PROVLN + '%') OR (@PROVLN IS NULL)) AND
				((M.REQUESTID = @REQUESTID) OR (M.REQUESTID LIKE @REQUESTID + '%') OR (@REQUESTID IS NULL))
				AND M.STATUSCODE NOT IN ('O','Q')
			ORDER BY M.authno DESC
		END

END






 

GO
