SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO




CREATE  procedure [dbo].[CHCNPortal_GetMembers]

-- UPDATED TO USE COBSUBSCRIBERID FIELD FOR PATID SEARCH
-- UPDATED [EZCAPDB2].[EZCAPDB].[dbo].CHCNPORTAL_MEMBMASTER_VS VIEW TO USE ECD.DBO.COB_MEMB_DETAILS TABLE
-- TO SEARCH ON ALL POSSIBLE PATIDS, CTA, 01/06/2014
-- UPDATED TO USE STATIC TABLE, REFRESHED NIGHTLY, CHCNPORTAL_MEMB_MASTER, CTA, 03/11/2014
-- Added PATID comparison for Healthplan ID SK.10/13/2016

@LASTNM nvarchar(50),
@FIRSTNM nvarchar(50),
@Patid nvarchar(50),
@DOB datetime, 
@Membid nvarchar(11)

as

If @LASTNM IS NULL AND @FIRSTNM IS NULL AND @Patid IS NULL AND @DOB IS NULL AND @Membid IS NULL 
	BEGIN
	RETURN
	END
ELSE
	BEGIN

SELECT  TOP 101 CAST(MEMB_KEYID AS varchar(max)) As MembKeyid, LASTNM, FIRSTNM, REV_FULLNAME, SEX, CONVERT(char(10),BIRTH,101) AS DOB, MEMBID, PATID, 
                      CONVERT(char(10),OPFROMDT,101) AS EFFDT, CONVERT(char(10),OPTHRUDT,101) AS TERMDT, 
		      STATUS, PCP, LEFT(OPT, LEN(OPT) - 3) AS OPTNAME, CLINIC, MEMOLINE1, MEMOLINE2, MEMOLINE3,MEMOLINE4,
			USERFIELD1, USERFIELD2, [LANGUAGE], NOTES 
FROM   DBO.CHCNPORTAL_MEMB_MASTER     -- [EZCAPDB2].[EZCAPDB].[dbo].CHCNPORTAL_MEMBMASTER_VS
WHERE   ((LASTNM = @LASTNM) or (LASTNM LIKE @LASTNM + '%') or (@LASTNM IS NULL)) and	
	((FIRSTNM = @FIRSTNM) or (FIRSTNM LIKE @FIRSTNM + '%') or (@FIRSTNM IS NULL)) and	
	(((AAH_ID = @Patid) or (AAH_ID  LIKE '%'+@Patid + '%') or (@PATID IS NULL)) OR
	((AAHS_ID = @Patid) or (AAHS_ID  LIKE '%'+@Patid + '%') or (@PATID IS NULL)) OR
	((AACC_ID = @Patid) or (AACC_ID  LIKE '%'+@Patid + '%') or (@PATID IS NULL)) OR
	((ANTHEM_ID = @Patid) or (ANTHEM_ID  LIKE '%'+@Patid + '%') or (@PATID IS NULL)) OR
	((HN_ID = @Patid) or (HN_ID  LIKE '%'+@Patid + '%') or (@PATID IS NULL)) OR
	((PATID = @Patid) or (PATID  LIKE '%'+@Patid + '%') or (@PATID IS NULL))) and
	((MEMBID = @Membid) or (MEMBID LIKE @Membid + '%') or (@MEMBID IS NULL)) and
	((BIRTH = @DOB) or (@DOB IS NULL))
ORDER BY LASTNM ASC, FIRSTNM, BIRTH ASC

END


GO
