SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO






-- ADDED PROCCODE_COMMON_ID FIELD, CTA, 11/30/2015
-- Added EXPIRED SK.5/12/2017
-- Added 'Paritally Approved' status and AUTHSTATUS in detail SK.2/13/2018

CREATE PROCEDURE [dbo].[CHCNPortal3_GetMemberAuthDetails]

@AUTHNUMBER varchar(25)

AS

If @AUTHNUMBER  IS NULL  
	BEGIN
	RETURN
	END
ELSE
BEGIN

SELECT   DISTINCT AUTHNUMBER, COMPANY_ID, 
STATUS = 	CASE WHEN [Status] = 'APPROVED' THEN 'APPROVED'
						WHEN [STATUS] = 'FUTURE ELECTIVE (APPROVED)' THEN 'APPROVED FUTURE ELECTIVE'
						WHEN [STATUS] = 'DEFERRED (FOR UM INFO)' THEN 'DEFERRED' 
						WHEN [STATUS] = 'PARTIALLY APPROVED' THEN 'PARTIALLY APPROVED' 
						--WHEN [STATUS] not in ('DEFERRED', 'CCS REFERRED', 'DENIED', 'CANCELLED') THEN 'SUBMITTED'
						WHEN [STATUS] not in ('CCS REFERRED', 'DENIED', 'CANCELLED','CCS APPROVED','EXPIRED') THEN 'SUBMITTED' 
						ELSE [STATUS] END,
 AUTHNO, CONVERT(char(10),REQDATE, 101) As REQDATE, 
	 CONVERT(char(10),AUTHDATE,101) AS AUTHDATE, CONVERT(char(10),EXPRDATE,101) AS EXPRDATE, 
	 REQPROV, RQPROVID, RENDPROV, REV_RENDPROV, MEMBID, PROCCODE, [DESCRIPTION] AS DESCR, CASENO, QTY, OPTDESC AS OPTNAME, VENDORNM,PLACESVC, MODIF, PHCODE, CERTTYPE, ONSETDT, CASE WHEN STATUSCODE IN('1','2','3','4','F') AND CERTTYPE IS NOT NULL AND ONSETDT IS NOT NULL THEN '1' ELSE '0' END AS AUTHLTR, MEMBNAME, PROCCODE_COMMON_ID
	 ,CASE WHEN AUTHSTATUS = 1 THEN 'APPROVED' WHEN AUTHSTATUS = 3 THEN 'DENIED' END AS AUTHSTATUS
FROM   [EZCAP65TEST].[EZCAPDB].[dbo].CHCNPortal_AUTHDetails_VS
WHERE  (AUTHNUMBER = @AUTHNUMBER)
ORDER BY AUTHNUMBER ASC

END






 

GO
