SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO




create PROCEDURE [dbo].[CHCNPORTAL_MAKE_CLAIM_MASTER]

AS

-- RUNS NIGHTLY, 01/22/2014, CTA
	
if exists (select * from dbo.sysobjects where id = object_id(N'[dbo].[CHCNPORTAL_CLAIM_MASTER]') and OBJECTPROPERTY(id, N'IsUserTable') = 1)
DROP TABLE [dbo].[CHCNPORTAL_CLAIM_MASTER]

SELECT * 
INTO [dbo].[CHCNPORTAL_CLAIM_MASTER]
FROM [EZCAP65TEST].[EZCAPDB].[dbo].[CHCNPORTAL_CLAIMMASTER_VS2]

	
CREATE INDEX VENDOR on CHCNPORTAL_CLAIM_MASTER(VENDOR)
CREATE INDEX CLAIMNO on CHCNPORTAL_CLAIM_MASTER(CLAIMNO)
CREATE INDEX MEMBID on CHCNPORTAL_CLAIM_MASTER(MEMBID)
CREATE INDEX PROVCLAIM on CHCNPORTAL_CLAIM_MASTER(PROVCLAIM)
CREATE INDEX PATID on CHCNPORTAL_CLAIM_MASTER(PATID)
CREATE INDEX LASTNM on CHCNPORTAL_CLAIM_MASTER(LASTNM)
CREATE INDEX FIRSTNM on CHCNPORTAL_CLAIM_MASTER(FIRSTNM)
























GO
