SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO



-- Added EXPIRED SK.5/12/2017

CREATE PROCEDURE [dbo].[CHCNPortal3_GetAuthDetails]

@AUTHNUMBER varchar(25)

AS

If @AUTHNUMBER  IS NULL  
	BEGIN
	RETURN
	END
ELSE
BEGIN

SELECT   DISTINCT AUTHNUMBER, COMPANY_ID, 
			STATUS = 	CASE WHEN [Status] = 'APPROVED' THEN 'APPROVED'
						WHEN [STATUS] = 'FUTURE ELECTIVE (APPROVED)' THEN 'APPROVED FUTURE ELECTIVE'
						WHEN [STATUS] = 'DEFERRED (FOR UM INFO)' THEN 'DEFERRED' 
						--WHEN [STATUS] not in ('DEFERRED', 'CCS REFERRED', 'DENIED', 'CANCELLED') THEN 'SUBMITTED'
						WHEN [STATUS] not in ('CCS REFERRED', 'DENIED', 'CANCELLED','CCS APPROVED','EXPIRED') THEN 'SUBMITTED' 
						ELSE [STATUS] END,
 CONVERT(char(10),REQDATE, 101) As REQDATE, 
	 CONVERT(char(10),AUTHDATE,101) AS AUTHDATE, CONVERT(char(10),EXPRDATE,101) AS EXPRDATE, 
	 REQPROV as RequestingProvider, RQPROVID as RequestingProviderID, RENDPROV, REV_RENDPROV, 
	 MEMBID, PROCCODE,DIAGCODE, [DESCRIPTION] AS DESCR, DIAGDESC, 
	 CASENO, QTY, OPTDESC AS OPTNAME, VENDORNM,PLACESVC, MODIF, PHCODE, CERTTYPE, ONSETDT, 
	 CASE WHEN STATUSCODE IN('1','2','4','F') AND CERTTYPE IS NOT NULL AND ONSETDT IS NOT NULL 
			THEN '1' ELSE '0' END AS AUTHLTR, 
	 CASE WHEN STATUSCODE = '3' 
			THEN '1' ELSE '0' END AS AUTH_DENIAL_LTR, 
	 MEMBNAME, 	 
	--isModified = CASE	WHEN (SELECT count(*) FROM [EZCAP65TEST].EZCAPDB.DBO.CSM_MASTERS_V 
	--					WHERE INCTYPE = 'MOD' AND CUSTCATEGORY = 'PROVIDER' AND  REFCATEGORY ='AUTHORIZATION'
	--					AND REFAUTHNO = AD.AUTHNO)>0 Then 'Yes' 
	--				WHEN (SELECT COUNT(*) FROM  [EZCAP65TEST].[EZCAPDB].[DBO].[AUTH_NOTES_V] WHERE AUTHNO = AD.AUTHNO 
	--					AND SUBJECT ='MOD') > 0 THEN 'Yes' ELSE 'No' End
	--Updated to include the active modification requests in Customer Service only (SK 9/23/2015)
	Modified = CASE WHEN (SELECT COUNT(*) FROM [EZCAP65TEST].EZCAPDB.DBO.CSM_MASTERS_V 
				WHERE INCTYPE = 'MOD' AND CUSTCATEGORY = 'PROVIDER' AND  REFCATEGORY ='AUTHORIZATION' AND STATUS = 'O'
				AND REFAUTHNO = AD.AUTHNO)>0 THEN 'Yes' ELSE 'No' END	
FROM   [DBO].[CHCNPORTAL_AUTH_DETAILS] AD
WHERE  (AUTHNUMBER = @AUTHNUMBER)
ORDER BY AUTHNUMBER ASC

END








GO
