SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO




CREATE PROCEDURE [dbo].[CHCNPDR_GetDisputesByAdvancedSearch]

--Updated EZCAP65TEST.EZCAPDB.dbo.CHCNPORTAL_CASEMASTER_VS

@USERID INT,
@PDRNO VARCHAR(25),
@CLAIMNO VARCHAR(25),
@LASTNM VARCHAR(20),
@FIRSTNM VARCHAR(10),
@DOB DATETIME,
@PROVLN VARCHAR(20)

AS 

IF @PDRNO IS NULL AND @CLAIMNO IS NULL AND @LASTNM IS NULL AND @FIRSTNM IS NULL AND @DOB IS NULL AND @PROVLN IS NULL
	RETURN
ELSE
BEGIN	
	DECLARE @COMPANYIDLIST varchar(150)	
	SET @COMPANYIDLIST = (SELECT DISTINCT REPLACE([Portal_DNN7].[dbo].CompanyIDList(@USERID),'-',''))			

	SELECT cm.CASENO AS PDRNO, cm.CLAIMNO, STUFF ((SELECT ', ' + CLAIMNO FROM EZCAP65TEST.EZCAPDB.dbo.CLAIM_PMASTERS_V WHERE CASENO = cm.CASENO FOR XML PATH('')), 1, 2, '') AS ALLCLAIMS, 
		OPENDT, CLOSEDT, ISNULL(LASTNM,'') + ',' + ISNULL(FIRSTNM,'') AS MEMB_NAME, 
		(SELECT DESCRIPTION FROM EZCAP65TEST.ECD.dbo.COMMON_CODES_V WHERE CATEGORY_NAME = 'CASESTATUS' AND CODE = cm.STATUS) AS STATUS,
		DATEFROM AS DOS, SPECCODE AS SpecialtyType,	
		CASE WHEN t.CNT > 1 THEN 1 ELSE 0 END AS IsClaimMulti, cm.STATUS AS STATUS_CODE
	FROM EZCAP65TEST.EZCAPDB.dbo.CHCNPORTAL_CASEMASTER_VS cm WITH (NOLOCK) INNER JOIN 
		(SELECT CASENO, MIN(CLAIMNO) AS CLAIMNO, COUNT(*) AS CNT FROM EZCAP65TEST.EZCAPDB.dbo.CHCNPORTAL_CASEMASTER_VS  WITH (NOLOCK)
			WHERE  (CHARINDEX(COMPANY_ID,@CompanyIDList)>0 or CHARINDEX(REPLACE(VENDOR,'-',''), @CompanyIDList)>0) 
						AND	CASETYPE IN ('A1','C1','D1','P1','R1','NC') GROUP BY CASENO) t 
		ON cm.CASENO = t.CASENO AND cm.CLAIMNO = t.CLAIMNO  	
	WHERE (cm.CASENO = @PDRNO OR cm.CASENO LIKE @PDRNO + '%' OR @PDRNO IS NULL) AND
		(ISNULL(cm.LASTNM,'') = @LASTNM OR ISNULL(cm.LASTNM,'') LIKE @LASTNM + '%' OR @LASTNM IS NULL) AND	
		(ISNULL(cm.FIRSTNM,'') = @FIRSTNM OR ISNULL(cm.FIRSTNM,'') LIKE @FIRSTNM + '%' OR @FIRSTNM IS NULL) AND	
		(cm.BIRTH = @DOB OR @DOB IS NULL) AND
		(cm.REV_FULLNAME = @PROVLN OR cm.REV_FULLNAME LIKE @PROVLN + '%' OR @PROVLN IS NULL) AND 
		(@CLAIMNO IN (SELECT CLAIMNO FROM EZCAP65TEST.EZCAPDB.dbo.CLAIM_PMASTERS_V WHERE CASENO = cm.CASENO)	OR @CLAIMNO IS NULL)
END




GO
