SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE PROCEDURE [dbo].[CHCNPORTAL_LOG_API_ENTRY]
 @ID UNIQUEIDENTIFIER,
 @LOGTIME DATETIME,
 @DURATION VARCHAR(50),
 @USERID VARCHAR(50),
 @REMOTE_IP VARCHAR(50),
 @REQUEST_URL VARCHAR(2000),
 @REQUEST_METHOD VARCHAR(10),
 @REQUEST_HEADERS VARCHAR(MAX),
 @REQUEST_BODY VARCHAR(MAX),
 @REQUEST_LENGTH VARCHAR(10),
 @RESPONSE_HEADERS VARCHAR(MAX),
 @RESPONSE_BODY VARCHAR(MAX),
 @RESPONSE_LENGTH VARCHAR(10),
 @STATUS_CODE VARCHAR(10)
 
 AS

 INSERT INTO [EZWEB].[dbo].[CHCNPORTAL_API_LOG]
			([ID]
           ,[LOGTIME]
           ,[DURATION]
           ,[USERID]
           ,[REMOTE_IP]
           ,[REQUEST_URL]
           ,[REQUEST_METHOD]
           ,[REQUEST_HEADERS]
           ,[REQUEST_BODY]
           ,[REQUEST_LENGTH]
           ,[RESPONSE_HEADERS]
           ,[RESPONSE_BODY]
           ,[RESPONSE_LENGTH]
           ,[STATUS_CODE])
     VALUES
           (@ID,
		   @LOGTIME,
		   @DURATION,
		   @USERID,
		   @REMOTE_IP,
		   @REQUEST_URL,
		   @REQUEST_METHOD,
		   @REQUEST_HEADERS,
		   @REQUEST_BODY,
		   @REQUEST_LENGTH,
		   @RESPONSE_HEADERS,
		   @RESPONSE_BODY,
		   @RESPONSE_LENGTH,
		   @STATUS_CODE)




GO
