SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO


CREATE PROCEDURE [dbo].[CHCNAuthGRID_GetCPT]

@CPT VARCHAR (20)

AS

IF @CPT IS NULL 
	BEGIN
	RETURN
	END
ELSE
	BEGIN
	
	SET @CPT = LTRIM(RTRIM(REPLACE(REPLACE(REPLACE(@CPT,CHAR(9),''),CHAR(10),''),CHAR(13),'')))	
	
SELECT  AUTH_GRID_ID, CODES_ID, RESTRICTIONS_ID, SVC_CODE, CATEGORY, SUB_CATEGORY, SVCDESC,IS_DUP,GRID_DETERM,HEALTHPLAN,COVERAGE,PROVID,PLACESVC,REST_DETERM,EFFECTIVE_DATE,TERM_DATE
FROM    [EZWEB].[DBO].[CHCNAUTH_FACT_V]
WHERE SVC_CODE LIKE @CPT+'%' OR (CHARINDEX(@CPT,SVCDESC) > 0) 	
END


GO
