SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO





CREATE PROCEDURE [dbo].[CHCNPortal_GetMemberClaimDetailsHeader]

-- UPDATED TO USE EZWEB.DBO.CHCNPORTAL_CLAIM_DETAILS TABLE - REFRESHED NIGHTLY, CTA, 01/22/2014
-- ADDED FACILITY AND AUTHNO FIELD PER SHAWNA LA CHAPELLE, CTA, 01/22/2014
-- Updated to use [EZCAP65TEST].[EZCAPDB].[dbo].[CHCNPORTAL_CLAIMDETAILS_VS2], 01/28/2016, CTA  

@CLAIMNO varchar(25)

AS
SELECT   DISTINCT CLAIMNO,DATERECD,STATUS, OPTDESC AS OPTNAME,MEMBID,TOTALNET,VENDOR,VENDORNM,DIAGCODE,DIAGDESC,PROVID,REV_FULLNAME,CASENO,IMAGE_URL, PROVCLAIM, CROSSREF_ID, MEMBNAME, AUTHNO, FACILITY
FROM   [EZCAP65TEST].[EZCAPDB].[dbo].[CHCNPORTAL_CLAIMDETAILS_VS2]
WHERE     (CLAIMNO = @CLAIMNO)

/*
SELECT   DISTINCT CLAIMNO,DATERECD,STATUS, OPTDESC AS OPTNAME,MEMBID,TOTALNET,VENDOR,VENDORNM,DIAGCODE,DIAGDESC,PROVID,REV_FULLNAME,CASENO,IMAGE_URL, PROVCLAIM, CROSSREF_ID, MEMBNAME, AUTHNO, FACILITY
FROM     DBO.CHCNPORTAL_CLAIM_DETAILS
WHERE     (CLAIMNO = @CLAIMNO)
*/





GO
