SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO



CREATE PROCEDURE [dbo].[CHCNAuthReq_GetCPT]

@RequestID varchar(30),
@CPT varchar (20)

as

If @RequestID IS NULL OR @CPT IS NULL 
	BEGIN
	RETURN
	END
ELSE
	BEGIN
	
	SET @CPT = LTRIM(RTRIM(REPLACE(REPLACE(REPLACE(@CPT,CHAR(9),''),CHAR(10),''),CHAR(13),'')))	
	
SELECT  COMMON_ID, PROCCODE, PROCDESC
FROM    [EZWEB].[DBO].[CHCNAUTHREQ_CPT]
WHERE PROCCODE like @CPT+'%' or (charindex(@CPT,PROCDESC) > 0) 	
End




GO
