SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO





-- =============================================
--SK.02/24/2017
-- To list all the past disputes without filtering dispute created date 
-- Will be used to prevent creating duplicate dispute for the same claim
-- =============================================
CREATE PROCEDURE [dbo].[CHCNPDR_GetDisputesOnEZCAP] 
	
	@USERID INT
AS
BEGIN
	
	SET NOCOUNT ON;

    DECLARE @COMPANYIDLIST varchar(150)	
	SET @COMPANYIDLIST = (SELECT DISTINCT REPLACE([Portal_DNN7].[dbo].CompanyIDList(@USERID),'-',''))			

	SELECT cm.CASENO AS PDRNO, cm.CLAIMNO, STUFF ((SELECT ', ' + CLAIMNO FROM EZCAP65TEST.EZCAPDB.dbo.CLAIM_PMASTERS_V WHERE CASENO = cm.CASENO FOR XML PATH('')), 1, 2, '') AS ALLCLAIMS, OPENDT, CLOSEDT, ISNULL(LASTNM,'') + ',' + ISNULL(FIRSTNM,'') AS MEMB_NAME, 
		(SELECT DESCRIPTION FROM EZCAP65TEST.ECD.dbo.COMMON_CODES_V WHERE CATEGORY_NAME = 'CASESTATUS' AND CODE = cm.STATUS) AS STATUS,
		DATEFROM AS DOS, SPECCODE AS SpecialtyType,	
		CASE WHEN t.CNT > 1 THEN 1 ELSE 0 END AS IsClaimMulti, cm.STATUS AS STATUS_CODE
	FROM EZCAP65TEST.EZCAPDB.dbo.CHCNPORTAL_CASEMASTER_VS cm WITH (NOLOCK) INNER JOIN 
		(SELECT CASENO, MIN(CLAIMNO) AS CLAIMNO, COUNT(*) AS CNT FROM EZCAP65TEST.EZCAPDB.dbo.CHCNPORTAL_CASEMASTER_VS  WITH (NOLOCK)
			WHERE  (CHARINDEX(COMPANY_ID,@CompanyIDList)>0 or CHARINDEX(REPLACE(VENDOR,'-',''), @CompanyIDList)>0) 
						AND	CASETYPE IN ('A1','C1','D1','P1','R1','NC') GROUP BY CASENO) t 
		ON cm.CASENO = t.CASENO AND cm.CLAIMNO = t.CLAIMNO		
					
END





GO
