SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO


CREATE PROCEDURE [dbo].[CHCNPORTAL_DASHBOARD_GET_USER_CLAIMS]
-- RETURNS CLAIMS COUNT FOR RENDERING TAX ID AND DATE RANGE SPECIFIED
-- CTA, 11/08/2017

@COMPANYID NVARCHAR(15),
@DATERANGE INT  -- NUMBER OF MONTHS FROM CURRENT DATE AS SELECTED FRM DASHBOARD DROP DOWN LIST

AS

DECLARE @DATESTART DATETIME

SET @DATESTART = DATEADD(M, -@DATERANGE, GETDATE()) 

SELECT COUNT(PM.CLAIMNO)
FROM [EZCAP65TEST].[EZCAPDB].[DBO].[CLAIM_PMASTERS] PM INNER JOIN
[EZCAP65TEST].[EZCAPDB].[dbo].[PROV_VENDINFO] AS PV WITH (NOLOCK) ON PM.PROV_KEYID = PV.PROV_KEYID 
WHERE PM.CREATEDATE BETWEEN @DATESTART AND GETDATE() AND 
(REPLACE(PV.VENDOR,'-','') = REPLACE(@COMPANYID,'-','')) 


GO
