SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO




--SK.1/29/2016 
--Validating NPI with Tax ID combination to store the validity in Local Admin log table


CREATE  PROCEDURE [dbo].[CHCNPortal3_ValidateNPI_WithTaxID]
	
	@TAXID VARCHAR(11),
	@NPI VARCHAR(25),
	@IsValidated BIT OUTPUT 
AS
IF @TAXID IS NULL OR @NPI IS NULL 
	RETURN
ELSE
BEGIN	

	SET @TAXID = REPLACE(@TAXID,'-','')

	IF EXISTS (SELECT * FROM [EZCAP65TEST].[EZCAPDB].[dbo].[CHCNEDI_CHC_SITES] WHERE REPLACE(VENDORID,'-','') = @TAXID AND NPI = @NPI)
		OR EXISTS (SELECT * FROM [EZCAP65TEST].[EZCAPDB].[dbo].[VEND_MASTERS_V] WHERE REPLACE(VENDORID,'-','') = @TAXID AND VENDOR_NPI = @NPI)
		OR EXISTS (SELECT * FROM [EZCAP65TEST].[EZCAPDB].[dbo].[PROV_COMPANY_V] pc INNER JOIN [EZCAP65TEST].[EZCAPDB].[dbo].[PROV_VENDINFO] pv
					ON pc.PROV_KEYID = pv.PROV_KEYID WHERE REPLACE(pv.VENDOR,'-','') = @TAXID AND pc.NPINO = @NPI)
		SET	@IsValidated = 1
	ELSE
		SET	@IsValidated = 0

END


GO
