SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO




CREATE   PROCEDURE [dbo].[CHCNAuthReq_MarkDUP]

@RequestID varchar(20),
@PROCCODE varchar(20),
@MODIF varchar(2),
@DIAGCODE varchar(10),
@DIAGREFNO int

as
DECLARE @prevDIAGREFNO int

SET @RequestID = LTRIM(RTRIM(REPLACE(REPLACE(REPLACE(@RequestID,CHAR(9),''),CHAR(10),''),CHAR(13),'')))
SET @PROCCODE = LTRIM(RTRIM(REPLACE(REPLACE(REPLACE(@PROCCODE,CHAR(9),''),CHAR(10),''),CHAR(13),'')))
SET @MODIF = LTRIM(RTRIM(REPLACE(REPLACE(REPLACE(@MODIF,CHAR(9),''),CHAR(10),''),CHAR(13),'')))
SET @DIAGCODE = LTRIM(RTRIM(REPLACE(REPLACE(REPLACE(@DIAGCODE,CHAR(9),''),CHAR(10),''),CHAR(13),'')))

INSERT INTO CHCNAuthReq_CPT_ICD_DUP_Temp (RequestID, PROCCODE, MODIF, DIAGCODE, DIAGREFNO)
VALUES (@REQUESTID, @PROCCODE, @MODIF, @DIAGCODE, @DIAGREFNO)









GO
