SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO



create proc [dbo].[CHCNPORTAL_MAKE_MEMB_HISTORY]

AS

-- RUNS NIGHTLY, 01/22/2014, CTA
	
if exists (select * from dbo.sysobjects where id = object_id(N'[dbo].[CHCNPORTAL_MEMB_HISTORY]') and OBJECTPROPERTY(id, N'IsUserTable') = 1)
DROP TABLE [dbo].[CHCNPORTAL_MEMB_HISTORY]

SELECT * 
INTO [dbo].[CHCNPORTAL_MEMB_HISTORY]
FROM  [EZCAP65TEST].[EZCAPDB].[DBO].[CHCNPORTAL_MEMB_HIST_VS]

	
CREATE INDEX MEMB_KEYID on CHCNPORTAL_MEMB_HISTORY(MEMB_KEYID)
CREATE INDEX MEMBID on CHCNPORTAL_MEMB_HISTORY(MEMBID)



GO
