SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO




-- Added code to strip out hyphens from COMPANYID comparison SK.5/17/2016
CREATE       PROCEDURE [dbo].[CHCNWEB_GetEOBMerritt]

-- 08/30/2012 CTA, updated for 6 digit check numbers
-- UPDATED TO ACCOMODATE EFTNO, CTA, 10/03/2014

@COMPANYID varchar(25),
@DTCHKLIST varchar(40)

AS

SET @COMPANYID = REPLACE(@COMPANYID,'-','') 

SELECT   CONVERT(char(10), DATEPAID, 101) AS DATEPD,OPT,LASTNM, FIRSTNM,CONVERT(char(10),BIRTH,101) AS DOB,SEX, PATID, 
	CONVERT(char(10),FROMDATESVC,101) AS DOSFROM,PROVCLAIM, LTRIM(PROCCODE) AS PROCCODE,MODIF, BILLED,
	  CONVERT(char(10),TODATESVC,101) AS DOSTO, CAPITATED, SEQUENCE,   
	 CONTRVAL,ADJUST,NET,INTEREST,ADJCODE,RTRIM(CONVERT(CHAR(10),CHPREFIX))AS CHPREFIX, CHECKNO = CASE WHEN CHECKNO = '0' THEN 'NO CHECK' ELSE RTRIM(CONVERT(CHAR(80),CHECKNO))END,
	CLAIMNO + ' - ' + LTRIM(STR(SEQUENCE)) AS CLAIMNO_SEQ, VENDNPI, MCALID
FROM       CHCNWEB_EOB
WHERE     REPLACE(VENDORID,'-','') = @COMPANYID AND (CONVERT(VARCHAR,DATEPAID,1) = RTRIM(LEFT(@DTCHKLIST,8))) AND 
	  (CHECKNO = CASE WHEN RTRIM(SUBSTRING(@DTCHKLIST,12,80))like '%CHECK%' THEN '0' ELSE RTRIM(SUBSTRING(@DTCHKLIST,12,80)) END)

















GO
