SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO




--Created on SK.7/12/2016 
--Read attachments related to messaging directly from EZCAP

CREATE PROCEDURE [dbo].[CHCNPortal3_GetUMMsgAttachment]
	@AUTHNO VARCHAR(25)	
AS
BEGIN
	
	SET NOCOUNT ON;
	   
    
    SELECT DISTINCT AUTHNO, FILENAME, Description, CAST(AUTHIMAGE AS VARBINARY(MAX)) AS ATTCHMENT, ReferenceID AS MessageID 	
	FROM [EZCAP65TEST].[EZCAPDB].[DBO].[CHCNEDI_AUTHIMAGES_VS] WITH (NOLOCK) 		
	WHERE AUTHNO = @AUTHNO AND ReferenceID IN (SELECT CONVERT(VARCHAR(25), MessageID) FROM dbo.CHCNPORTAL3_MESSAGE_LOG WHERE AUTHNO = @AUTHNO) 
    
    
END



GO
