SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO





CREATE PROCEDURE [dbo].[CHCNAuthReq_GetRequestingProvUnlisted]

AS 

SELECT DISTINCT PROV_KEYID, PROVID, FULLNAME, MEDICAL_GROUP, DESCR AS SPECIALTY, CITY, [CONTRACT], SPECCODE
FROM  [EZCAP65TEST].[EZCAPDB].DBO.CHCNPORTAL_SPECIALISTS_RVS
where PROVID='UNKNOWNNPI2'





GO
