SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO



CREATE proc [dbo].[CHCNPORTAL_MAKE_AUTH_NOTES]

AS

-- RUNS NIGHTLY, 01/22/2014, CTA
	
if exists (select * from dbo.sysobjects where id = object_id(N'[dbo].[CHCNPORTAL_AUTH_NOTES]') and OBJECTPROPERTY(id, N'IsUserTable') = 1)
DROP TABLE [dbo].[CHCNPORTAL_AUTH_NOTES]

SELECT * 
INTO [dbo].[CHCNPORTAL_AUTH_NOTES]
FROM  EZCAP65TEST.EZCAPDB.dbo.AUTH_NOTES_VS

	
CREATE INDEX AUTHNO on CHCNPORTAL_AUTH_NOTES(AUTHNO)



GO
