SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO








CREATE PROCEDURE [dbo].[CHCNPDR_GetResolutionLetter]
	
	@PDRNO VARCHAR(25)
	
AS
BEGIN
	
	SET NOCOUNT ON;

   	SELECT DISTINCT CAST(PDRIMAGE AS VARBINARY(MAX)) AS PDRIMAGE	
	FROM [EZCAP65TEST].[EZCAPDB].[DBO].[CHCNEDI_PDRIMAGES_VS] WITH (NOLOCK) 		
	--WHERE CASENO = @PDRNO AND ReferenceID IN ('RL','RESOLUTION LETTER') AND Contenttype = 'application/pdf'		
	WHERE CASENO = @PDRNO AND Description IN ('RL','RESOLUTION LETTER') AND Contenttype = 'application/pdf'		
END









GO
