SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO




--Added Facility Name SK.1/19/2017 
--Added EXPIRED SK.5/12/2017
-- Added 'Paritally Approved' status SK.2/13/2018

CREATE PROCEDURE [dbo].[CHCNPortal3_GetMemberAuthDetailsHeader]

@AUTHNUMBER varchar(25)

AS

SELECT  DISTINCT AUTHNUMBER,  AUTHNO = CASE WHEN STATUSCODE IN ('1','2') THEN ad.AUTHNO WHEN STATUSCODE='7' THEN ad.STATUS ELSE 'PENDING' END, 
ad.REQDATE,ad.AUTHDATE, ad.EXPRDATE, 
STATUS = 	CASE WHEN ad.[Status] = 'APPROVED' THEN 'APPROVED'
						WHEN ad.[STATUS] = 'FUTURE ELECTIVE (APPROVED)' THEN 'APPROVED FUTURE ELECTIVE'
						WHEN ad.[STATUS] = 'DEFERRED (FOR UM INFO)' THEN 'DEFERRED'
						WHEN ad.[STATUS] = 'PARTIALLY APPROVED' THEN 'PARTIALLY APPROVED' 
						--WHEN ad.[STATUS] not in ('DEFERRED', 'CCS REFERRED', 'DENIED', 'CANCELLED') THEN 'SUBMITTED'
						WHEN ad.[STATUS] not in ('CCS REFERRED', 'DENIED', 'CANCELLED','CCS APPROVED','EXPIRED') THEN 'SUBMITTED' 
						ELSE ad.[STATUS] END,
OPTDESC AS OPTNAME,ad.MEMBID,RQPROVID,VENDORNM,DIAGCODE,DIAGDESC,RENDPROV,REV_RENDPROV,ad.CASENO, QTY, ad.MEMBNAME, pc.REV_FULLNAME AS FACILITY_NAME
FROM   EZCAP65TEST.[EZCAPDB].[dbo].CHCNPortal_AUTHDetails_VS ad INNER JOIN EZCAP65TEST.EZCAPDB.dbo.AUTH_MASTERS_V am ON ad.AUTHNUMBER = am.AUTHNO
LEFT JOIN EZCAP65TEST.EZCAPDB.dbo.PROV_COMPANY_V pc ON am.SVCFACID_KEYID = pc.PROV_KEYID
WHERE     (AUTHNUMBER = @AUTHNUMBER)










GO
