SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO




CREATE PROCEDURE [dbo].[CHCNPORTAL_MAKE_MEMB_MASTER]

AS

-- RUNS NIGHTLY, 01/22/2014, CTA
	
if exists (select * from dbo.sysobjects where id = object_id(N'[dbo].[CHCNPORTAL_MEMB_MASTER]') and OBJECTPROPERTY(id, N'IsUserTable') = 1)
DROP TABLE [dbo].[CHCNPORTAL_MEMB_MASTER]

SELECT * 
INTO [dbo].[CHCNPORTAL_MEMB_MASTER]
FROM  [EZCAP65TEST].[EZCAPDB].[dbo].[CHCNPORTAL_MEMBMASTER_VS]

	
CREATE INDEX MEMB_KEYID on CHCNPORTAL_MEMB_MASTER(MEMB_KEYID)
CREATE INDEX MEMBID on CHCNPORTAL_MEMB_MASTER(MEMBID)
CREATE INDEX AAH_ID on CHCNPORTAL_MEMB_MASTER(AAH_ID)
CREATE INDEX AAHS_ID on CHCNPORTAL_MEMB_MASTER(AAHS_ID)
CREATE INDEX AACC_ID on CHCNPORTAL_MEMB_MASTER(AACC_ID)
CREATE INDEX ANTHEM_ID on CHCNPORTAL_MEMB_MASTER(ANTHEM_ID)
CREATE INDEX HN_ID on CHCNPORTAL_MEMB_MASTER(HN_ID)
CREATE INDEX LASTNM on CHCNPORTAL_MEMB_MASTER(LASTNM)
CREATE INDEX FIRSTNM on CHCNPORTAL_MEMB_MASTER(FIRSTNM)
























GO
