SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO



-- Stored Procedure

CREATE PROCEDURE [dbo].[CHCNPortal3_GetAllAuths]

-- AUTH used for displaying "My AUTH" and "My Company AUTH" tabs
-- ToDo: include AUTH submitted using the OLD AUTH FORM in My Authorization
-- Added DEFERRED,'CCS APPROVED' SK 4/6/2016 requested by AT 
-- Added EXPIRED SK 5/12/2017
-- Count all letters SK.8/29/2017 (ZIRA PRIOR-918) 
-- Added to filter auth status in ('O','Q') SK.9/26/2017
-- Added 'Paritally Approved' status SK.2/13/2018


@FROMDT datetime,
@TODT datetime,
@USERID NVARCHAR(5)

AS 

IF @USERID IS NULL OR @FROMDT IS NULL OR @TODT IS NULL 
	RETURN
ELSE
BEGIN
	DECLARE @COMPANYIDLIST varchar(150)
	--SET @COMPANYIDLIST = (SELECT DISTINCT [Portal_DNN7].[dbo].CompanyIDList(@USERID))
	SET @COMPANYIDLIST = (SELECT DISTINCT REPLACE([Portal_DNN7].[dbo].CompanyIDList(@USERID),'-',''))		

	SELECT 	DISTINCT M.AUTHNO, 
			CONVERT(char(10),M.REQDATE, 101) As Submit_Date,
			--Modified = CASE WHEN (SELECT count(*) FROM [EZCAP65TEST].EZCAPDB.DBO.CSM_MASTERS_V 
			--			WHERE INCTYPE = 'MOD' AND CUSTCATEGORY = 'PROVIDER' AND  REFCATEGORY ='AUTHORIZATION'
			--			AND REFAUTHNO = M.AUTHNO)>0 Then 'Yes' 
			--			WHEN (SELECT COUNT(*) FROM  [EZCAP65TEST].[EZCAPDB].[DBO].[AUTH_NOTES_V] WHERE AUTHNO = M.AUTHNO AND SUBJECT ='MOD') > 0 THEN 'Yes' ELSE 'No' End,
			--Updated to include the active modification requests in Customer Service only (SK 9/23/2015)
			Modified = CASE WHEN (SELECT COUNT(*) FROM [EZCAP65TEST].EZCAPDB.DBO.CSM_MASTERS_V WITH (NOLOCK) 
						WHERE INCTYPE = 'MOD' AND CUSTCATEGORY = 'PROVIDER' AND  REFCATEGORY ='AUTHORIZATION' AND STATUS = 'O'
						AND REFAUTHNO = M.AUTHNO)>0 THEN 'Yes' ELSE 'No' END,
			M.MEMBNAME, CONVERT(char(10),M.BIRTH,101) As DateOfBirth,
			STATUS = 	CASE WHEN M.[Status] = 'APPROVED' THEN 'APPROVED'
						WHEN M.[STATUS] = 'FUTURE ELECTIVE (APPROVED)' THEN 'APPROVED FUTURE ELECTIVE'
						WHEN M.[STATUS] = 'DEFERRED (FOR UM INFO)' THEN 'DEFERRED' 
						WHEN M.[STATUS] = 'PARTIALLY APPROVED' THEN 'PARTIALLY APPROVED' 
						WHEN M.[STATUS] not in ('CCS REFERRED', 'DENIED', 'CANCELLED','CCS APPROVED','EXPIRED') THEN 'SUBMITTED' 
						ELSE M.[STATUS] END,
			M.OnsetDT as DecisionDate, 
			--Shows the attachment count only for denial letter. Team decided for temporary. SK.1/20/2016 --Count all letters SK.8/29/2017 (ZIRA PRIOR-918) 
			AttachmentCount = (	SELECT COUNT(*) FROM [EZCAP65TEST].[EZCAPDB].[DBO].[CHCNEDI_AUTHIMAGES_VS] AS ATT WITH (NOLOCK) 
													INNER JOIN [EZCAP65TEST].[EZCAPDB].[DBO].[AUTH_MASTERS_V] AM WITH (NOLOCK) ON ATT.AUTHNO = AM.AUTHNO
								WHERE ATT.AUTHNO=M.AUTHNO AND ((ATT.ReferenceID IN ('DENIAL LETTER') AND AM.STATUS = '3')
															OR (ATT.ReferenceID IN ('DEFERRED LETTER') AND AM.STATUS = '9')
															OR (ATT.ReferenceID LIKE '%RECLASSIFICATION NOTICE%')
															OR (ATT.Description = 'APPROVAL LETTER' AND AM.STATUS LIKE '[1PV]'))), 	
			M.AUTHDATE,
			M.SPECCODE, MBeta.UserID,lm.IsRead,lm.LastMsgReadDt
			,M.PRIORITY_STATUS_DESC AS REQUEST_TYPE
	FROM	[EZCAP65TEST].[EZCAPDB].[dbo].[CHCNPORTAL_AUTHMASTER_VS] as M  WITH (NOLOCK) LEFT JOIN CHCNAuthReq_Master MBeta  WITH (NOLOCK) ON M.AUTHNO=MBeta.EZCAP_AuthNo
			LEFT JOIN (SELECT AuthNo, MAX(ReadDate) AS LastMsgReadDt, MIN(CAST(IsRead AS INT)) AS IsRead FROM CHCNPORTAL3_MESSAGE_LOG GROUP BY AuthNo) lm ON M.AUTHNO = lm.AuthNo 
	WHERE (CHARINDEX(M.COMPANY_ID,@CompanyIDList)>0 or CHARINDEX(REPLACE(M.RQPROVID,'-',''), @CompanyIDList)>0 or 
			CHARINDEX(REPLACE(M.RENDPROVID,'-',''), @CompanyIDList)>0 or CHARINDEX(REPLACE(M.CLINIC,'-',''), @CompanyIDList)>0 or 
			CHARINDEX(REPLACE(M.FACILITYID,'-',''), @CompanyIDList)>0) 
			AND	(CAST(M.REQDATE AS DATETIME) BETWEEN @FROMDT AND @TODT) AND M.STATUSCODE NOT IN ('O','Q')
	UNION
	-- GET DRAFT REQUESTS WHERE A MEMBER IS ALREADY SELECTED AND FILTER ONLY ON THE REQUESTING PROVIDER'S TAX ID
	-- lchu 12/3/15 updated to only show draft created by the given userID
	SELECT REQUESTID AS AUTHNO, ISNULL(RequestDate, LastModifiedDate) AS SUBMIT_DATE, MODIFIED = 'No', MEMBNAME, DATEOFBIRTH='', STATUS = 'DRAFT', DECISIONDATE = NULL, 
	ATTACHMENTCOUNT= 0, --(SELECT COUNT(*) FROM CHCNAuthReq_Attachments_Temp WHERE REQUESTID = MDraft.RequestID), 
	MDraft.SERVICESTARTDATE AS AUTHDATE, MDraft.REFTOSPEC AS SPECCODE, 
	MDraft.UserID, 1 AS IsRead, NULL AS LastMsgReadDt
	,CASE WHEN MDraft.RequestType = 'U' THEN 'URGENT' WHEN MDraft.RequestType = 'R' THEN 'RETRO' ELSE 'STANDARD' END AS REQUEST_TYPE 
	FROM CHCNAuthReq_Master MDraft WITH (NOLOCK) 
	WHERE UserID=@UserID AND DraftMode = 1 AND (MDraft.LastModifiedDate BETWEEN @FROMDT AND @TODT) 
	ORDER BY authno desc

END




 

GO
