SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO




-- Added code to strip out hyphens from COMPANYID comparison SK.5/17/2016

CREATE             PROCEDURE [dbo].[CHCNWEB_GetEOBSummary]

--10/18/2007	CTA	Include null CHECKNO
-- 08/30/2012 CTA, updated for 6 digit check numbers
-- Added CAST on CHECKNO to fix conversion issue., CTA, 04/28/2014
-- UPDATED TO ACCOMODATE EFTNO, CTA, 10/03/2014


@COMPANYID varchar(25),
@DTCHKLIST varchar(40)

AS

SET @COMPANYID = REPLACE(@COMPANYID,'-','') 

SELECT  VENDORNM AS VENDOR, VENDORID AS TAXID, SUM(NET) AS TOTALNET, 
                      SUM(BILLED) AS TOTALBILLED, SUM(INTEREST) AS TOTALINTEREST, CHECKNO = CASE WHEN CHECKNO = '0' THEN 'NO CHECK' ELSE CAST(CHECKNO as VARCHAR(80)) END, 
                      DATEPAID
FROM   CHCNWEB_EOB_SUMMARY_VS
WHERE     (REPLACE(VENDORID,'-','') = @COMPANYID) AND (CONVERT(VARCHAR,DATEPAID,1) = RTRIM(LEFT(@DTCHKLIST,8))) AND
	  (CHECKNO = CASE WHEN RTRIM(SUBSTRING(@DTCHKLIST,12,80))like '%CHECK%' THEN '0' ELSE RTRIM(SUBSTRING(@DTCHKLIST,12,80)) END)
GROUP BY VENDORID, VENDORNM, CHECKNO, DATEPAID
























GO
