SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO



CREATE proc [dbo].[CHCNPORTAL_MAKE_AUTH_MASTER]

AS

-- RUNS NIGHTLY, 01/22/2014, CTA
	
if exists (select * from dbo.sysobjects where id = object_id(N'[dbo].[CHCNPORTAL_AUTH_MASTER]') and OBJECTPROPERTY(id, N'IsUserTable') = 1)
DROP TABLE [dbo].[CHCNPORTAL_AUTH_MASTER]

SELECT * 
INTO [dbo].[CHCNPORTAL_AUTH_MASTER]
FROM     [EZCAP65TEST].[EZCAPDB].dbo.CHCNPortal_AuthMaster_VS 

	
CREATE INDEX AUTHNO on CHCNPORTAL_AUTH_MASTER(AUTHNO)
CREATE INDEX LASTNM on CHCNPORTAL_AUTH_MASTER(LASTNM)
CREATE INDEX FIRSTNM on CHCNPORTAL_AUTH_MASTER(FIRSTNM)
CREATE INDEX MEMBID on CHCNPORTAL_AUTH_MASTER(MEMBID)
CREATE INDEX PROVNAME on CHCNPORTAL_AUTH_MASTER(PROVNAME)
CREATE INDEX AAH_ID on CHCNPORTAL_AUTH_MASTER(AAH_ID)
CREATE INDEX AAHS_ID on CHCNPORTAL_AUTH_MASTER(AAHS_ID)
CREATE INDEX ANTHEM_ID on CHCNPORTAL_AUTH_MASTER(ANTHEM_ID)
CREATE INDEX RequestID on CHCNPORTAL_AUTH_MASTER(REQUESTID)



GO
