SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO



-- ========================================================================
-- SK 9/24/2015
-- To get Auth Notes for subject line = ‘CAN / CANCEL’ (cancelled) or ‘MOD’ (modification)
-- Updated to include MOD note from Customer Service module when a open ticket exists (11/04/2015) 
-- Changed Subject 'Modification' to 'Revision' SK.10/13/2016
-- ========================================================================
CREATE PROCEDURE [dbo].[CHCNPortal3_GetAuthNotes]
	
	@AUTHNUMBER VARCHAR(25)
AS
BEGIN
	
	SET NOCOUNT ON;
	DECLARE @SQL VARCHAR(MAX) 	

	--SELECT NOTES, SUBJECT 
	--FROM [EZCAP65TEST].[EZCAPDB].[DBO].[AUTH_NOTES] WITH (NOLOCK) 
	--WHERE AUTHNO = @AUTHNO AND LTRIM(RTRIM(SUBJECT)) IN ('CAN','CANCEL','MOD')	

	SET @SQL = 'SELECT CASE WHEN SUBJECT IN (''CAN'',''CANCEL'',''CANCELLED'') THEN ''CANCELLED'' ' 
	SET @SQL =  @SQL + ' WHEN SUBJECT IN (''DEF'',''DEFERRED'',''DEFER'') THEN ''DEFERRED'' '
	SET @SQL =  @SQL + ' WHEN SUBJECT IN (''MOD'',''MODIFIED'',''MODIFICATION'',''MODIFY'') THEN ''REVISION'' '
	SET @SQL =  @SQL + ' WHEN SUBJECT IN (''DNLR'') THEN ''DENIAL REASON'' END AS SUBJECT, NOTES '
	SET @SQL =  @SQL + ' FROM ('
	SET @SQL =  @SQL + 'SELECT SUBJECT, NOTES, MAX(CREATEDATE) AS CREATEDATE
						FROM [EZCAP65TEST].[EZCAPDB].[DBO].[AUTH_NOTES] WITH (NOLOCK) 
						WHERE AUTHNO = ' + @AUTHNUMBER + ' AND LTRIM(RTRIM(SUBJECT)) IN (''CAN'',''CANCEL'',''CANCELLED'') 
						GROUP BY SUBJECT, NOTES	
						UNION ALL '
	SET @SQL =  @SQL + 'SELECT SUBJECT, NOTES, MAX(CREATEDATE) AS CREATEDATE
						FROM [EZCAP65TEST].[EZCAPDB].[DBO].[AUTH_NOTES] WITH (NOLOCK) 
						WHERE AUTHNO = ' + @AUTHNUMBER + ' AND LTRIM(RTRIM(SUBJECT)) IN (''DEF'',''DEFERRED'',''DEFER'') 
						GROUP BY SUBJECT, NOTES		
						UNION ALL '
	SET @SQL =  @SQL + 'SELECT SUBJECT, NOTES, MAX(CREATEDATE) AS CREATEDATE
						FROM [EZCAP65TEST].[EZCAPDB].[DBO].[AUTH_NOTES] WITH (NOLOCK) 
						WHERE AUTHNO = ' + @AUTHNUMBER + ' AND LTRIM(RTRIM(SUBJECT)) IN (''DNLR'')	
						GROUP BY SUBJECT, NOTES
						UNION ALL '
	--Added 'CCS APPROVED' Note SK 4/6/2016 requested by AT 
	SET @SQL =  @SQL + 'SELECT SUBJECT, NOTES, MAX(CREATEDATE) AS CREATEDATE
						FROM [EZCAP65TEST].[EZCAPDB].[DBO].[AUTH_NOTES] WITH (NOLOCK) 
						WHERE AUTHNO = ' + @AUTHNUMBER + ' AND LTRIM(RTRIM(SUBJECT)) IN (''SAR'')	
						GROUP BY SUBJECT, NOTES
						UNION ALL '
		
	IF EXISTS (SELECT * FROM [EZCAP65TEST].EZCAPDB.DBO.CSM_MASTERS_V 
				WHERE INCTYPE = 'MOD' AND CUSTCATEGORY = 'PROVIDER' AND  REFCATEGORY ='AUTHORIZATION' AND STATUS = 'O' AND REFAUTHNO = @AUTHNUMBER)
		BEGIN
			SET @SQL = @SQL + 'SELECT SUBJECT, NOTES, MAX(cn.CREATEDATE) AS CREATEDATE
								FROM [EZCAP65TEST].[EZCAPDB].[dbo].[CSM_NOTES] cn WITH (NOLOCK) INNER JOIN [EZCAP65TEST].EZCAPDB.DBO.CSM_MASTERS_V cm ON cn.CSINO = cm.CSINO
								WHERE cm.REFAUTHNO = ' + @AUTHNUMBER + ' AND LTRIM(RTRIM(cn.SUBJECT)) IN (''MOD'',''MODIFIED'',''MODIFICATION'',''MODIFY'') AND cm.CUSTCATEGORY = ''PROVIDER'' AND  cm.REFCATEGORY =''AUTHORIZATION'' AND cm.STATUS = ''O'' 
								GROUP BY SUBJECT, NOTES '	
		END
	ELSE
		BEGIN
			SET @SQL = @SQL + 'SELECT SUBJECT, NOTES, MAX(CREATEDATE) AS CREATEDATE
								FROM [EZCAP65TEST].[EZCAPDB].[DBO].[AUTH_NOTES] WITH (NOLOCK) 
								WHERE AUTHNO = ' + @AUTHNUMBER + ' AND LTRIM(RTRIM(SUBJECT)) IN (''MOD'',''MODIFIED'',''MODIFICATION'',''MODIFY'') 
								GROUP BY SUBJECT, NOTES '	
		END
	
	SET @SQL =  @SQL + 'UNION ALL 
						SELECT ''DNLR'' AS SUBJECT, ''CHCN has denied your request for services. You will receive a faxed copy of the denial letter explaining the denial reason within 1 business day.'' AS NOTES, GETDATE() AS CREATEDATE
						 FROM [EZCAP65TEST].[EZCAPDB].[DBO].[AUTH_MASTERS_V] WITH (NOLOCK)
						 WHERE AUTHNO = ' + @AUTHNUMBER + ' AND STATUS = ''3'' 
							AND AUTHNO NOT IN (SELECT AUTHNO FROM [EZCAP65TEST].[EZCAPDB].[DBO].[AUTH_NOTES] WITH (NOLOCK) WHERE SUBJECT = ''DNLR'')'

	SET @SQL =  @SQL + ') A ORDER BY CREATEDATE DESC'
	
	EXEC (@SQL)
		    
END



GO
