SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO



-- Added code to strip out hyphens from VENDORID comparison SK.5/17/2016

CREATE    PROCEDURE [dbo].[CHCNAuthReq_GetPCPs]

@VendorID varchar(10),
@PROVIDER varchar(20)
as

SET @PROVIDER = LTRIM(RTRIM(REPLACE(REPLACE(REPLACE(@PROVIDER,CHAR(9),''),CHAR(10),''),CHAR(13),'')))	
SET @VendorID = REPLACE(@VendorID,'-','') 

SELECT PROV_KEYID, PROVID, REV_FULLNAME AS REVNAME, VENDOR
FROM  [EZWEB].[DBO].[REQUESTING_PROV]
WHERE REPLACE(vendor,'-','') = @VendorID AND LASTNAME LIKE @PROVIDER+'%'


GO
