SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO




-- =============================================
--SK.11/16/2016
-- =============================================
CREATE PROCEDURE [dbo].[CHCNPDR_GetDisputeDetails]  
	
	@PDRNO VARCHAR(25)
AS
BEGIN
	
	SET NOCOUNT ON;   
	

	SELECT DISTINCT cm.CASENO, STUFF ((SELECT ', ' + CLAIMNO FROM EZCAP65TEST.EZCAPDB.dbo.CLAIM_PMASTERS_V WHERE CASENO = cm.CASENO FOR XML PATH('')), 1, 2, '') AS CLAIMNO,
	OPENDT, CLOSEDT, ISNULL(mc.LASTNM,'') + ',' + ISNULL(mc.FIRSTNM,'') AS MEMB_NAME, mc.BIRTH, pc.REV_FULLNAME, --cp.ADMDATE AS DOS, 
	(SELECT DESCRIPTION FROM EZCAP65TEST.ECD.dbo.COMMON_CODES_V WHERE CATEGORY_NAME = 'CASESTATUS' AND CODE = cm.STATUS) AS STATUS,	
	cm.COMPANY_ID, ATTENDPROV_KEYID, ATTENDPROVID, cm.MEMB_KEYID, pv.VENDOR
	FROM EZCAP65TEST.EZCAPDB.dbo.CASE_MASTERS_V cm WITH (NOLOCK)
		LEFT JOIN EZCAP65TEST.EZCAPDB.dbo.MEMB_COMPANY_V mc WITH (NOLOCK) ON cm.MEMB_KEYID = mc.MEMB_KEYID
		LEFT JOIN EZCAP65TEST.EZCAPDB.dbo.PROV_COMPANY_V pc WITH (NOLOCK) ON cm.ATTENDPROV_KEYID = pc.PROV_KEYID
		LEFT JOIN EZCAP65TEST.EZCAPDB.dbo.PROV_VENDINFO_V pv WITH (NOLOCK) ON pc.PROV_KEYID = pv.PROV_KEYID
		--LEFT JOIN EZCAP65TEST.EZCAPDB.dbo.CLAIM_PMASTERS_V cp WITH (NOLOCK) ON cp.CASENO = cm.CASENO
	WHERE  cm.CASENO = @PDRNO
	ORDER BY CASENO DESC


	
END




GO
