SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO





CREATE procedure [dbo].[CHCNAuthReq_GetMembers]

@LASTNM nvarchar(50),
@FIRSTNM nvarchar(50),
@PATID nvarchar(20),
@DOB datetime

as

If @LASTNM IS NULL AND @FIRSTNM IS NULL AND @Patid IS NULL AND @DOB IS NULL 
	BEGIN
	RETURN
	END
ELSE
	BEGIN

		SET @LASTNM = LTRIM(RTRIM(REPLACE(REPLACE(REPLACE(@LASTNM,CHAR(9),''),CHAR(10),''),CHAR(13),'')))	
		SET @FIRSTNM = LTRIM(RTRIM(REPLACE(REPLACE(REPLACE(@FIRSTNM,CHAR(9),''),CHAR(10),''),CHAR(13),'')))
		SET @PATID = LTRIM(RTRIM(REPLACE(REPLACE(REPLACE(@PATID,CHAR(9),''),CHAR(10),''),CHAR(13),'')))
		SET @DOB = LTRIM(RTRIM(REPLACE(REPLACE(REPLACE(@DOB,CHAR(9),''),CHAR(10),''),CHAR(13),'')))

		
		SELECT * FROM
		(SELECT *, ROW_NUMBER() OVER(PARTITION BY PATID ORDER BY CoveragePriority ASC, EFFDT DESC) AS rk	
		 FROM
		(
		SELECT  TOP 101 CAST(MEMB_KEYID AS varchar(max)) As MembKeyid, LASTNM, FIRSTNM, 
				REV_FULLNAME, SEX, CONVERT(char(10),BIRTH,101) AS DOB, MEMBID, PATID,
				CONVERT(char(10),OPFROMDT,101) AS EFFDT, CONVERT(char(10),OPTHRUDT,101) AS TERMDT, 
				STATUS, PCP + ' ' + CLINIC as PCP_FULL, LEFT(OPT, LEN(OPT) - 3) AS OPTNAME
				, CASE LEFT(OPT, LEN(OPT) - 3)
					WHEN 'AAGC' THEN 1
					WHEN 'AACC' THEN 2
					WHEN 'AAMM' THEN 3
					ELSE '4'
				END AS CoveragePriority	
		FROM   [EZCAP65TEST].[EZCAPDB].[dbo].CHCNPORTAL_MEMBMASTER_VS
		WHERE   ((@LASTNM IS NULL) or (LASTNM = @LASTNM) or (LASTNM LIKE @LASTNM + '%')) and	
			((@FIRSTNM IS NULL) or (FIRSTNM = @FIRSTNM) or (FIRSTNM LIKE @FIRSTNM + '%')) and	
			((@PATID IS NULL) or (PATID = @Patid) or (PATID  LIKE '%'+@Patid + '%')) and
			((@DOB IS NULL) or (BIRTH = @DOB))
		ORDER BY CoveragePriority asc, effdt) AS A) as B
		WHERE B.rk = 1 
		ORDER BY LASTNM ASC, FIRSTNM, DOB ASC

END




GO
