SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO



CREATE proc [dbo].[CHCNPORTAL_MAKE_AUTH_MEMOS]

AS

-- RUNS NIGHTLY, 01/22/2014, CTA
	
if exists (select * from dbo.sysobjects where id = object_id(N'[dbo].[CHCNPORTAL_AUTH_MEMOS]') and OBJECTPROPERTY(id, N'IsUserTable') = 1)
DROP TABLE [dbo].[CHCNPORTAL_AUTH_MEMOS]

SELECT * 
INTO [dbo].[CHCNPORTAL_AUTH_MEMOS]
FROM    EZCAP65TEST.EZCAPDB.dbo.AUTH_MEMOFLDS_VS

	
CREATE INDEX AUTHNO on CHCNPORTAL_AUTH_MEMOS(AUTHNO)



GO
