SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO



-- =============================================
-- SK.1/18/2017
-- Provider dispute detail information to generate Ack letter in Crystal report
-- CTA.01/24/2017
-- ADDED @INFOREQ AND @DETERM VARIABLES TO INITIALIZE COLUMNS WITH PROPER DATATYPES
-- SETTING COLUMNS TO EQUAL NULL SETS DATATYPE TO INT BY DEFAULT 
-- CHANGED @ADDL_INFO = ADDL_INFO TO ADDL_INFO = @ADDL_INFO
-- =============================================
CREATE PROCEDURE [dbo].[CHCNPDR_GetAckLetterDetail]

	@RequestID VARCHAR(30),
	@PDRNO VARCHAR(25)	
	
AS
BEGIN
	
	SET NOCOUNT ON;
	DECLARE @AddlInfo VARCHAR(1) = 'N'
	DECLARE @INFOREQ VARCHAR(MAX) = NULL -- ADDED TO INITIALIZE FIELD AS A VARCHAR(MAX), CTA, 01/24/2017
	DECLARE @DETERM VARCHAR(MAX) = NULL  -- ADDED TO INITIALIZE FIELD AS A VARCHAR(MAX), CTA, 01/24/2017
 


    SELECT DISTINCT EZCAP_CaseNo AS CASENO, CLAIMNO, CONVERT(VARCHAR,EZCAP_PostDt,101) AS ONSETDT, Claim_Billed AS BILLED,
		Claim_Prov AS PROVCLAIM, MEMBID, Claim_MembName AS MEMBNAME, CONVERT(VARCHAR,Claim_DateFrom,101) AS DOSFROM, CONVERT(VARCHAR,Claim_DateTo,101) AS DOSTO,
		Claim_VendorNM AS VENDORNM, Submitter_Street +CHAR(13)+CHAR(10)+ [Submitter_City] + ', ' + [Submitter_State] + ' ' + [Submitter_Zip] AS ADDRESS,
		ISNULL(Submitter_ProvName,'') AS CONTACT, ADDL_INFO = @AddlInfo,Claim_ProcCode AS PROCCODE,
		INFOREQ = @INFOREQ, Claim_OPT AS OPT, NULL AS CLOSEDT, DETERM = @DETERM
    FROM dbo.CHCNPDR_Master 
	WHERE RequestID = @RequestID AND EZCAP_CaseNo = @PDRNO
		
END




GO
