SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO




-- =============================================
--SK.11/16/2016
-- Added All Claim numbers as a separate column - D.Streicher 02/03/2017
-- =============================================
CREATE PROCEDURE [dbo].[CHCNPDR_GetDisputes] 
	
	@USERID INT
AS
BEGIN
	
	SET NOCOUNT ON;

    DECLARE @COMPANYIDLIST VARCHAR(150)	
	SET @COMPANYIDLIST = (SELECT DISTINCT REPLACE([Portal_DNN7].[dbo].CompanyIDList(@USERID),'-',''))		
	

	--SELECT CASENO AS PDRNO, CLAIMNO, OPENDT, CLOSEDT, ISNULL(LASTNM,'') + ',' + ISNULL(FIRSTNM,'') AS MEMB_NAME, 
	--CASE WHEN STATUS = 'R' THEN 'RESOLVED' ELSE 'SUBMITTED' END AS STATUS, DATEFROM AS DOS, SPECCODE AS SpecialtyType	
	--FROM EZCAP65TEST.EZCAPDB.dbo.CHCNPORTAL_CASEMASTER_VS
	--WHERE  (CHARINDEX(COMPANY_ID,@CompanyIDList)>0 or CHARINDEX(REPLACE(VENDOR,'-',''), @CompanyIDList)>0) 
	--			AND	OPENDT > DATEADD(MONTH, -1, GETDATE()) 
	--			AND CASETYPE IN ('A1','C1','D1','P1','R1','NC')	

	SELECT cm.CASENO AS PDRNO, cm.CLAIMNO, STUFF ((SELECT ', ' + CLAIMNO FROM EZCAP65TEST.EZCAPDB.dbo.CLAIM_PMASTERS_V WHERE CASENO = cm.CASENO FOR XML PATH('')), 1, 2, '') AS ALLCLAIMS, OPENDT, CLOSEDT, ISNULL(LASTNM,'') + ',' + ISNULL(FIRSTNM,'') AS MEMB_NAME, 
		--CASE WHEN STATUS = 'R' THEN 'RESOLVED' ELSE 'OPEN' END AS STATUS, 
		(SELECT DESCRIPTION FROM EZCAP65TEST.ECD.dbo.COMMON_CODES_V WHERE CATEGORY_NAME = 'CASESTATUS' AND CODE = cm.STATUS) AS STATUS,
		DATEFROM AS DOS, SPECCODE AS SpecialtyType,	
		CASE WHEN t.CNT > 1 THEN 1 ELSE 0 END AS IsClaimMulti, cm.STATUS AS STATUS_CODE
	FROM EZCAP65TEST.EZCAPDB.dbo.CHCNPORTAL_CASEMASTER_VS cm WITH (NOLOCK) INNER JOIN 
		(SELECT CASENO, MIN(CLAIMNO) AS CLAIMNO, COUNT(*) AS CNT FROM EZCAP65TEST.EZCAPDB.dbo.CHCNPORTAL_CASEMASTER_VS  WITH (NOLOCK)
			WHERE  (CHARINDEX(COMPANY_ID,@CompanyIDList)>0 OR CHARINDEX(REPLACE(VENDOR,'-',''), @CompanyIDList)>0) 
						AND	OPENDT > DATEADD(MONTH, -1, GETDATE()) AND CASETYPE IN ('A1','C1','D1','P1','R1','NC') GROUP BY CASENO) t 
		ON cm.CASENO = t.CASENO AND cm.CLAIMNO = t.CLAIMNO		
				
	UNION
	SELECT RequestID AS PDRNO, ClaimNo, NULL AS ALLCLAIMS,NULL AS OPENDT, NULL AS CLOSEDT, ISNULL(Memb_LName,'') + ',' + ISNULL(Memb_FName,'') AS MEMB_NAME, 'DRAFT' AS STATUS, ServiceDate AS DOS, SpecialtyType, 0 AS IsClaimMulti,'' AS STATUS_CODE
	FROM CHCNPDR_Master 
	WHERE UserID = @USERID AND DraftMode = 1 AND EnterDate > DATEADD(MONTH, -1, GETDATE())
	ORDER BY PDRNO DESC

	
	
END




GO
