SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO




--SK.7/12/2016 
--Insert attachments to temp table

CREATE PROCEDURE [dbo].[CHCNPortal3_InsertUMMsgAttachmentTemp]
	@AUTHNO VARCHAR(25),
	@FILENAME VARCHAR(200),
	@DESCRIPTION VARCHAR(500),
	@CONTENTTYPE VARCHAR(100),
	@ATTACHMENT VARBINARY(MAX),	
	@RetValue VARCHAR(200) = '' OUTPUT
AS
BEGIN
	
	SET NOCOUNT ON;

	BEGIN TRY
	BEGIN TRAN
		
		SET @FILENAME = LTRIM(RTRIM(REPLACE(REPLACE(REPLACE(@Filename,CHAR(9),''),CHAR(10),''),CHAR(13),'')))	
		SET @CONTENTTYPE = LTRIM(RTRIM(REPLACE(REPLACE(REPLACE(@ContentType,CHAR(9),''),CHAR(10),''),CHAR(13),'')))	
		SET @DESCRIPTION = LTRIM(RTRIM(REPLACE(REPLACE(REPLACE(@Description,CHAR(9),''),CHAR(10),''),CHAR(13),'')))	

		INSERT INTO CHCNAuthReq_Attachments_Temp (RequestID, [FileName], DESCR, CONTENTTYPE, ATTACHMENT, MSG_FLAG)
		VALUES (@AUTHNO, @FILENAME, @DESCRIPTION, @CONTENTTYPE, @ATTACHMENT, 1)
		
		COMMIT TRAN
	    
    END TRY
	BEGIN CATCH
		--SELECT ERROR_NUMBER(),ERROR_SEVERITY(),ERROR_STATE(),ERROR_PROCEDURE() 
		SET @RetValue = 'Error Line: ' + CAST(ERROR_LINE() AS VARCHAR(50)) + ', Error Message: ' + ERROR_MESSAGE();
		IF (@@TRANCOUNT > 0)
			ROLLBACK TRAN				
	END CATCH	
    
END



GO
