SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO



--Added provider class and description fields -- Need to update [EZCAPDB].DBO.CHCNPORTAL_SPECIALISTS_RVS to list CLASS and CLASS_DESC SK.7/7/2016

CREATE PROCEDURE [dbo].[CHCNAuthReq_GetRequestedProvByFacility]

@IN_PROVFACILITY  VARCHAR(30) -- Search Criteria

AS 

DECLARE @FACILITY_CONTRACT CHAR(1) = 'H'

SELECT DISTINCT PROV_KEYID, PROVID, FULLNAME, MEDICAL_GROUP, DESCR AS SPECIALTY, CITY, @FACILITY_CONTRACT as [CONTRACT], SPECCODE, STREET,
CASE	WHEN PHONE IS NULL OR PHONE = '--' OR PHONE = '-' THEN '' ELSE PHONE END as PHONE,
CASE	WHEN FAX IS NULL OR FAX = '--' OR FAX = '-' THEN '' ELSE FAX END as FAX, CLASS AS PROVCLASS, CLASS_DESC AS PROVCLASS_DESC
FROM  [EZCAP65TEST].[EZCAPDB].DBO.CHCNPORTAL_SPECIALISTS_RVS
WHERE  LASTNAME LIKE @IN_PROVFACILITY+'%' AND PROVID not in ('UNKNOWNNPI', 'UNKNOWNNPI2') AND CLASS = 'H' --SPECCODE = N'HOS'
ORDER BY FULLNAME ASC



GO
