SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO



CREATE PROCEDURE [dbo].[CHCNAuthReq_GetRequestedProvBySpecialistMedicalGroup]

@SPECCODE VARCHAR(3),
@MEDICAL_GROUP VARCHAR(300)
 
AS

DECLARE @SPECIALIST_CONTRACT CHAR(1) = 'S'

IF @MEDICAL_GROUP = '--Select a Medical Group (Optional)--'
BEGIN
SELECT DISTINCT PROV_KEYID, PROVID, FULLNAME, MEDICAL_GROUP, CITY, DESCR AS SPECIALTY, SPECCODE, @SPECIALIST_CONTRACT AS [CONTRACT], 
CASE	WHEN PHONE IS NULL OR PHONE = '--' OR PHONE = '-' THEN '' ELSE PHONE END as PHONE,
CASE	WHEN FAX IS NULL OR FAX = '--' OR FAX = '-' THEN '' ELSE FAX END as FAX
FROM  [EZCAP65TEST].[EZCAPDB].DBO.CHCNPORTAL_SPECIALISTS_RVS
WHERE  SPECCODE = @SPECCODE and [CONTRACT] <> 'N' 
ORDER BY MEDICAL_GROUP, FULLNAME
END

ELSE
BEGIN
SELECT DISTINCT PROV_KEYID, PROVID, FULLNAME, MEDICAL_GROUP, CITY, DESCR AS SPECIALTY, SPECCODE, @SPECIALIST_CONTRACT AS [CONTRACT], 
CASE	WHEN PHONE IS NULL OR PHONE = '--' OR PHONE = '-' THEN '' ELSE PHONE END as PHONE,
CASE	WHEN FAX IS NULL OR FAX = '--' OR FAX = '-' THEN '' ELSE FAX END as FAX
FROM  [EZCAP65TEST].[EZCAPDB].DBO.CHCNPORTAL_SPECIALISTS_RVS
WHERE  SPECCODE = @SPECCODE and (MEDICAL_GROUP = @MEDICAL_GROUP or nullif(MEDICAL_GROUP,'') is null)
and [CONTRACT] <> 'N' ORDER BY FULLNAME ASC
END


GO
