SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO




CREATE PROCEDURE [dbo].[CHCNPortal_GetMemberAuthsCt]
-- ADDED CLINIC FIELD TO SEARCH FILTER, CTA, 01/07/2014
-- UPDATED TO USE STATIC TABLE, CHCNPORTAL_AUTH_MASTER, CTA, 03/11/2014
-- Added code to strip out hyphens from COMPANYID comparison SK.5/17/2016
-- Added filtering for Alameda Alliance and Anthem, CTA, 06/17/2016

@MemberID varchar(20),
@CompanyID varchar(500)

AS
IF @MEMBERID IS NULL AND @COMPANYID IS NULL  
	BEGIN
	RETURN
	END
ELSE
	BEGIN

	SET @COMPANYID = REPLACE(@COMPANYID,'-','') 

	IF @COMPANYID LIKE '%ALAMEDA%' -- Updated to use wildcard, CTA, 06/23/2013
		BEGIN
			SELECT     COUNT(DISTINCT AUTHNO) AS Count
			FROM    DBO.CHCNPORTAL_AUTH_MASTER--     EZCAP65TEST.EZCAPDB.dbo.CHCNPortal_AuthMaster_VS AS CHCNPortal_AuthMaster_VS
			WHERE     (MEMBID = @MEMBERID)and OPT LIKE 'AA%'
		END

	ELSE IF @COMPANYID LIKE '%ANTHEM%' -- Updated to use wildcard, CTA, 06/23/2013
		BEGIN
			SELECT     COUNT(DISTINCT AUTHNO) AS Count
			FROM    DBO.CHCNPORTAL_AUTH_MASTER--     EZCAP65TEST.EZCAPDB.dbo.CHCNPortal_AuthMaster_VS AS CHCNPortal_AuthMaster_VS
			WHERE     (MEMBID = @MEMBERID)and OPT LIKE 'BC%'
		END

	ELSE 
		BEGIN
			SELECT     COUNT(DISTINCT AUTHNO) AS Count
			FROM    DBO.CHCNPORTAL_AUTH_MASTER--     EZCAP65TEST.EZCAPDB.dbo.CHCNPortal_AuthMaster_VS AS CHCNPortal_AuthMaster_VS
			WHERE     (MEMBID = @MEMBERID)and ((CHARINDEX(REPLACE(COMPANY_ID,'-',''),@COMPANYID)>0) OR (CHARINDEX(REPLACE(RQPROVID,'-',''),@COMPANYID)>0 ) or (CHARINDEX(REPLACE(RENDPROVID,'-',''),@COMPANYID)>0) or (CHARINDEX(REPLACE(CLINIC,'-',''),@COMPANYID)>0))
		END
	END



GO
