SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO


CREATE PROCEDURE [dbo].[CHCNPORTAL_MAKE_PROVIDERS]

AS


if exists (select * from dbo.sysobjects where id = object_id(N'[dbo].[CHCNPORTAL_PROVIDERS]') and OBJECTPROPERTY(id, N'IsUserTable') = 1)
DROP TABLE [dbo].[CHCNPORTAL_PROVIDERS]

SELECT DISTINCT  PV.VENDOR, PC.PROV_KEYID, PC.PROVID, PC.REV_FULLNAME AS REVNAME, PC.FULLNAME, PC.FIRSTNAME, PC.LASTNAME
INTO CHCNPORTAL_PROVIDERS
FROM  [EZCAP65TEST].[EZCAPDB].[DBO].[PROV_COMPANY_V] PC JOIN [EZCAP65TEST].[EZCAPDB].[DBO].[PROV_VENDINFO_V] PV ON PC.PROV_KEYID=PV.PROV_KEYID
WHERE (PC.FIRSTNAME IS NOT NULL) AND (NULLIF(PC.TERMDATE,'') IS NULL)
ORDER BY VENDOR, REVNAME ASC

CREATE INDEX VENDOR ON CHCNPORTAL_PROVIDERS (VENDOR)
CREATE INDEX PROVID ON CHCNPORTAL_PROVIDERS (PROVID)


GO
