SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO





CREATE PROCEDURE [dbo].[CHCNAuthReq_GetCPTSelected]

@RequestID varchar(20)

as

SET @RequestID = LTRIM(RTRIM(REPLACE(REPLACE(REPLACE(@RequestID,CHAR(9),''),CHAR(10),''),CHAR(13),'')))

SELECT DISTINCT CPT.ID, CPT.RequestID, CPT.ProcCode, CPT.ProcDesc, CPT.Qty, 
	Case When CPT.Modif='-1' THEN '' Else CPT.Modif END as Modif, 
	DUP = (CASE WHEN DUP.RequestID IS NULL THEN 0 ELSE 1 END)
FROM CHCNAuthReq_CPT_Temp CPT left join CHCNAuthReq_CPT_ICD_DUP_Temp DUP
ON CPT.REQUESTID=DUP.REQUESTID AND CPT.PROCCODE = DUP.PROCCODE AND CPT.MODIF = DUP.MODIF
WHERE CPT.RequestID = @RequestID





GO
