SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO











--SK.08/21/2017
CREATE PROCEDURE [dbo].[CHCNPortal3_GetAuthApprovalLetter]
	
	@AUTHNO VARCHAR(25)
	
AS
BEGIN
	
	SET NOCOUNT ON;

 --  	SELECT CAST(AUTHIMAGE AS VARBINARY(MAX)) AS AUTHIMAGE
	----SELECT @IMAGEFILE = AUTHIMAGE  
	--FROM [EZCAP65TEST].[EZCAPDB].[DBO].[CHCNEDI_AUTHIMAGES_VS] ai WITH (NOLOCK) 
	--	INNER JOIN [EZCAP65TEST].[EZCAPDB].[DBO].AUTH_MASTERS_V am WITH (NOLOCK) ON ai.AUTHNO = am.AUTHNO
	--WHERE ai.AUTHNO = @AUTHNO AND am.STATUS LIKE '[1PV]'
	--	AND (ai.Description = 'APPROVAL LETTER') 
	--	AND ai.Contenttype = 'application/pdf'	
		
	
	SELECT DISTINCT ai.Description, ai.Contenttype, CAST(AUTHIMAGE AS VARBINARY(MAX)) AS AUTHIMAGE	
	INTO #temp_AuthImages
	FROM [EZCAP65TEST].[EZCAPDB].[DBO].[CHCNEDI_AUTHIMAGES_VS] ai WITH (NOLOCK) 
		INNER JOIN [EZCAP65TEST].[EZCAPDB].[DBO].AUTH_MASTERS_V am WITH (NOLOCK) ON ai.AUTHNO = am.AUTHNO
	WHERE ai.AUTHNO = @AUTHNO AND am.STATUS LIKE '[1PV]'

	SELECT AUTHIMAGE from #temp_AuthImages WHERE Description = 'APPROVAL LETTER' AND Contenttype = 'application/pdf'	

	DROP TABLE #temp_AuthImages
		
END







GO
