SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO



create proc [dbo].[CHCNPORTAL_MAKE_MEMB_OTHCOV]

AS

-- RUNS NIGHTLY, 01/22/2014, CTA
	
if exists (select * from dbo.sysobjects where id = object_id(N'[dbo].[CHCNPORTAL_MEMB_OTHCOV]') and OBJECTPROPERTY(id, N'IsUserTable') = 1)
DROP TABLE [dbo].[CHCNPORTAL_MEMB_OTHCOV]

SELECT * 
INTO [dbo].[CHCNPORTAL_MEMB_OTHCOV]
FROM  [EZCAP65TEST].[EZCAPDB].[dbo].[CHCN_OMID_VS]

	
CREATE INDEX MEMB_KEYID on CHCNPORTAL_MEMB_OTHCOV(MEMB_KEYID)
CREATE INDEX MEMBID on CHCNPORTAL_MEMB_OTHCOV(MEMBID)



GO
