SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO



CREATE PROCEDURE [dbo].[CHCNPORTAL_MAKE_AUTHREQPROVIDERS]

AS


if exists (select * from dbo.sysobjects where id = object_id(N'[dbo].[CHCNPORTAL_AUTHREQPROVIDERS]') and OBJECTPROPERTY(id, N'IsUserTable') = 1)
DROP TABLE [dbo].[CHCNPORTAL_AUTHREQPROVIDERS]

SELECT DISTINCT PROV_KEYID,VENDOR,VENDORNM, PROVID, REVNAME, FULLNAME, FIRSTNAME, LASTNAME, [CONTRACT], CONTRACT_DESCR, SPECCODE, SPECDESCR, FROMDATE, TERMDATE
INTO CHCNPORTAL_AUTHREQPROVIDERS
FROM  [EZCAP65TEST].[EZCAPDB].DBO.CHCNPORTAL_REQPROVS_VS 
WHERE (FIRSTNAME IS NOT NULL) AND (NULLIF(TERMDATE,'') IS NULL)
ORDER BY VENDOR, REVNAME ASC

CREATE INDEX VENDOR ON CHCNPORTAL_AUTHREQPROVIDERS (VENDOR)
CREATE INDEX PROVID ON CHCNPORTAL_AUTHREQPROVIDERS (PROVID)


GO
