SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO



CREATE proc [dbo].[CHCNPORTAL_MAKE_AUTH_DETAILS]

AS

-- RUNS NIGHTLY, 01/22/2014, CTA
	
if exists (select * from dbo.sysobjects where id = object_id(N'[dbo].[CHCNPORTAL_AUTH_DETAILS]') and OBJECTPROPERTY(id, N'IsUserTable') = 1)
DROP TABLE [dbo].[CHCNPORTAL_AUTH_DETAILS]

SELECT * 
INTO [dbo].[CHCNPORTAL_AUTH_DETAILS]
FROM    [EZCAP65TEST].[EZCAPDB].[dbo].CHCNPortal_AUTHDetails_VS

	
CREATE INDEX AUTHNUMBER on CHCNPORTAL_AUTH_DETAILS(AUTHNUMBER)



GO
