CREATE TABLE [dbo].[CHCNPORTAL_AuthReq_Master_bak]
(
[RequestID] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[UserID] [nchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[Email] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RequestType] [int] NOT NULL,
[CHCNReq] [bit] NULL,
[RequestDate] [datetime] NOT NULL,
[AuthFromDate] [datetime] NULL,
[AuthToDate] [datetime] NULL,
[ReqName] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ReqPhone] [varchar] (12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ReqFax] [varchar] (12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ReqFacility] [varchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ReqProvName] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ReqProvID] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Req_Prov_KeyID] [uniqueidentifier] NULL,
[ReqSpec] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[UnlistedProv] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MembID] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Memb_Keyid] [uniqueidentifier] NULL,
[MembName] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MembDOB] [datetime] NULL,
[BenOPT] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PatID] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[HPCode] [varchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RefToProvID] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RefTo_Prov_KeyID] [uniqueidentifier] NULL,
[RefToSpec] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RefToSpecialty] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RefToName] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RefToCompanyID] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RefToCompanyName] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RefContract] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RefToMembReq] [bit] NULL,
[RefToLanguage] [bit] NULL,
[RefToLocation] [bit] NULL,
[RefToContinuity] [bit] NULL,
[RefToOnlyProv] [bit] NULL,
[RefToOther] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SerType] [int] NULL,
[SerConsult] [bit] NULL,
[SerTreatment] [bit] NULL,
[SerInpAdm] [bit] NULL,
[SerOutSurgHosp] [bit] NULL,
[SerDME] [bit] NULL,
[SerOutSurgFree] [bit] NULL,
[SerHHC] [bit] NULL,
[SerHHCDesc] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SerDiagTest] [bit] NULL,
[SerQty] [int] NULL,
[SerPOS] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SvcClinicalDesc] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Attachment] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CurrScreen] [int] NULL,
[Submitted] [bit] NULL,
[Completed] [bit] NULL,
[FaxRecDt] [datetime] NULL,
[AuthNo] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Notify] [bit] NULL,
[StatusChange] [int] NULL,
[NotifyDate] [datetime] NULL
) ON [PRIMARY]
GO
