CREATE TABLE [dbo].[CHCNWEB_MEMBERS]
(
[MEMB_KEYID] [uniqueidentifier] NULL,
[MEMB_MPI_NO] [uniqueidentifier] NULL,
[MEMBID] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MEMBSSN] [varchar] (9) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SUBSSN] [varchar] (9) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PATID] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RLSHIP] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[STATUS] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LASTNM] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FIRSTNM] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[REV_FULLNAME] [varchar] (113) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SEX] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BIRTH] [datetime] NULL,
[MARITAL] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[WORKPHONE] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EXTENSION] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FAX] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EMAIL] [varchar] (80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LANGUAGE] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ETHNICITY] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[STREET] [varchar] (80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[STREET2] [varchar] (80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CITY] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ZIP] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PHONE] [varchar] (24) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OTHCOV] [bit] NULL,
[OTHPRIM] [int] NULL,
[OTHNAME] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MEMOLINE1] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MEMOLINE2] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MEMOLINE3] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MEMOLINE4] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PCP] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PCPFROMDT] [datetime] NULL,
[PCPTHRUDT] [datetime] NULL,
[TRANDATE] [datetime] NULL,
[OPFROMDT] [datetime] NULL,
[OPTHRUDT] [datetime] NULL,
[HPFROMDT] [datetime] NULL,
[HPCODE] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OPT] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[HMO] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[HP] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CHC] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CREATEDATE] [datetime] NULL,
[SITE] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[USERFIELD1] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[USERFIELD2] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[HFPCOPAY] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
