CREATE TABLE [dbo].[CHCNWEB_SPECIALISTS]
(
[ID] [int] NOT NULL IDENTITY(1, 1),
[FULLNAME] [varchar] (80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LASTNAME] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FIRSTNAME] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PROVID] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[STREET] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CITY] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ZIP] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PHONE] [varchar] (12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FAX] [varchar] (12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[HOSPITAL] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DESCR] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CODE] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MEMOLINE3] [varchar] (82) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LANGUAGE] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MEDICAL_GROUP] [varchar] (75) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PANEL_INFO] [varchar] (210) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AREA_OF_FOCUS] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NPINO] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RESTRICTIONS] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [WEB_CITY] ON [dbo].[CHCNWEB_SPECIALISTS] ([CITY]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [WEB_CODE] ON [dbo].[CHCNWEB_SPECIALISTS] ([CODE]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [WEB_ID] ON [dbo].[CHCNWEB_SPECIALISTS] ([ID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [WEB_LN] ON [dbo].[CHCNWEB_SPECIALISTS] ([LASTNAME]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [WEB_PROVID] ON [dbo].[CHCNWEB_SPECIALISTS] ([PROVID]) ON [PRIMARY]
GO
