CREATE TABLE [dbo].[CHCNPORTAL_MEMB_OTHCOV]
(
[MEMB_KEYID] [uniqueidentifier] NOT NULL,
[MEMBID] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[PATID] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OPT] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OPFROMDT] [datetime] NOT NULL,
[OPTHRUDT] [datetime] NULL,
[SEQUENCE] [int] NOT NULL,
[TYPE] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OUTSIDEID] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FROMDATE] [datetime] NOT NULL,
[TODATE] [datetime] NULL,
[CREATEDATE] [datetime] NOT NULL,
[CREATEBY] [int] NULL,
[HPCODE] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [MEMB_KEYID] ON [dbo].[CHCNPORTAL_MEMB_OTHCOV] ([MEMB_KEYID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [MEMBID] ON [dbo].[CHCNPORTAL_MEMB_OTHCOV] ([MEMBID]) ON [PRIMARY]
GO
