CREATE TABLE [dbo].[CHCNWEB_PATID_REF]
(
[MEMBID] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PATID] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [WEB_MEMBID] ON [dbo].[CHCNWEB_PATID_REF] ([MEMBID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [WEB_PATID] ON [dbo].[CHCNWEB_PATID_REF] ([PATID]) ON [PRIMARY]
GO
