CREATE TABLE [dbo].[CHCNPORTAL_SPECIALISTS]
(
[ID] [int] NOT NULL IDENTITY(1, 1),
[PROV_KEYID] [uniqueidentifier] NULL,
[FULLNAME] [varchar] (8000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LASTNAME] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FIRSTNAME] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PROVID] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[STREET] [varchar] (80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CITY] [varchar] (80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ZIP] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PHONE] [varchar] (12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FAX] [varchar] (12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[HOSPITAL] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DESCR] [varchar] (300) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CODE] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MEMOLINE3] [varchar] (82) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LANGUAGE] [varchar] (300) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MEDICAL_GROUP] [varchar] (75) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CONTRACT] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [WEB_CITY2] ON [dbo].[CHCNPORTAL_SPECIALISTS] ([CITY]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [WEB_CODE2] ON [dbo].[CHCNPORTAL_SPECIALISTS] ([CODE]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [WEB_ID2] ON [dbo].[CHCNPORTAL_SPECIALISTS] ([ID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [WEB_LN2] ON [dbo].[CHCNPORTAL_SPECIALISTS] ([LASTNAME]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [WEB_PROVIDKEYID] ON [dbo].[CHCNPORTAL_SPECIALISTS] ([PROV_KEYID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [WEB_PROVID2] ON [dbo].[CHCNPORTAL_SPECIALISTS] ([PROVID]) ON [PRIMARY]
GO
