CREATE TABLE [dbo].[CHCNWEB_REFDIAGS]
(
[COMMON_ID] [int] NULL,
[DIAGCODE] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DIAGDESC] [varchar] (300) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[VERSION] [int] NULL
) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [WEB_DXID] ON [dbo].[CHCNWEB_REFDIAGS] ([COMMON_ID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [WEB_DXCODE] ON [dbo].[CHCNWEB_REFDIAGS] ([DIAGCODE]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [WEB_DXDESC] ON [dbo].[CHCNWEB_REFDIAGS] ([DIAGDESC]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [WEB_VERSION] ON [dbo].[CHCNWEB_REFDIAGS] ([VERSION]) ON [PRIMARY]
GO
