CREATE TABLE [dbo].[CHCNAUTH_CODES]
(
[CODES_ID] [int] NOT NULL IDENTITY(1, 1),
[SVCCODE] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SVCDESC] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CHCNAUTH_CODES] ADD CONSTRAINT [PK_CHCNAUTH_CODES] PRIMARY KEY CLUSTERED  ([CODES_ID]) ON [PRIMARY]
GO
