CREATE TABLE [dbo].[CHCNPORTAL_PROVIDERS]
(
[VENDOR] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[PROV_KEYID] [uniqueidentifier] NOT NULL,
[PROVID] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[REVNAME] [varchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FULLNAME] [varchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FIRSTNAME] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LASTNAME] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [PROVID] ON [dbo].[CHCNPORTAL_PROVIDERS] ([PROVID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [VENDOR] ON [dbo].[CHCNPORTAL_PROVIDERS] ([VENDOR]) ON [PRIMARY]
GO
