CREATE TABLE [dbo].[CHCNAUTH_GRID]
(
[AUTH_GRID_ID] [int] NOT NULL IDENTITY(1, 1),
[CATEGORY] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SUB_CATEGORY] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SVC_CODE] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DESCRIPTION] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[IS_DUP] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[GRID_DETERM] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CHCNAUTH_GRID] ADD CONSTRAINT [PK_CHCNAUTH_GRID] PRIMARY KEY CLUSTERED  ([AUTH_GRID_ID]) ON [PRIMARY]
GO
