CREATE TABLE [dbo].[CHCNPORTAL_CLAIM_NOTES]
(
[CLAIMNO] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[Subject] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Notes] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [CLAIMNO] ON [dbo].[CHCNPORTAL_CLAIM_NOTES] ([CLAIMNO]) ON [PRIMARY]
GO
