CREATE TABLE [dbo].[CHCNPORTAL_AUTH_MASTER]
(
[AUTHNO] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[PLACESVC] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[STATUSCODE] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MEMBID] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LASTNM] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FIRSTNM] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MEMBNAME] [varchar] (72) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BIRTH] [datetime] NULL,
[PATID] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[STATUS] [varchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[COMPANY_ID] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RQPROVID] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[REQDATE] [char] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AUTHDATE] [char] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EXPRDATE] [char] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[REQPROV] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RENDPROV] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RENDPROVID] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PROV_LN] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PROV_FN] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PROVNAME] [varchar] (72) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PROVID] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CLINIC] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PCP] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OPT] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AUTHUNITS] [smallint] NULL,
[ONSETDT] [char] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AAH_ID] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AAHS_ID] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AACC_ID] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ANTHEM_ID] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[HN_ID] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RequestID] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FACPROVID] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FACILITYID] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SPECCODE] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PRIORITY_STATUS_CODE] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PRIORITY_STATUS_DESC] [varchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [AAH_ID] ON [dbo].[CHCNPORTAL_AUTH_MASTER] ([AAH_ID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [AAHS_ID] ON [dbo].[CHCNPORTAL_AUTH_MASTER] ([AAHS_ID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [ANTHEM_ID] ON [dbo].[CHCNPORTAL_AUTH_MASTER] ([ANTHEM_ID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [AUTHNO] ON [dbo].[CHCNPORTAL_AUTH_MASTER] ([AUTHNO]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [FIRSTNM] ON [dbo].[CHCNPORTAL_AUTH_MASTER] ([FIRSTNM]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [LASTNM] ON [dbo].[CHCNPORTAL_AUTH_MASTER] ([LASTNM]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [MEMBID] ON [dbo].[CHCNPORTAL_AUTH_MASTER] ([MEMBID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [PROVNAME] ON [dbo].[CHCNPORTAL_AUTH_MASTER] ([PROVNAME]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [RequestID] ON [dbo].[CHCNPORTAL_AUTH_MASTER] ([RequestID]) ON [PRIMARY]
GO
