CREATE TABLE [dbo].[CHCNPORTAL_CLAIM_MASTER]
(
[CLAIMNO] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[PROVID] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[VENDOR] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[BILLED] [numeric] (15, 2) NOT NULL,
[PROVCLAIM] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[COMPANY_ID] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[STATUS] [varchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LASTNM] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FIRSTNM] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MEMBNAME] [varchar] (72) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MEMBID] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PATID] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PROVNAME] [varchar] (72) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DATEFROM] [char] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DATETO] [char] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BIRTH] [char] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DATERECD] [char] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DATEPAID] [char] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CASENO] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AAH_ID] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AAHS_ID] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AACC_ID] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ANTHEM_ID] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[HN_ID] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OPT] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [CLAIMNO] ON [dbo].[CHCNPORTAL_CLAIM_MASTER] ([CLAIMNO]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [FIRSTNM] ON [dbo].[CHCNPORTAL_CLAIM_MASTER] ([FIRSTNM]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [LASTNM] ON [dbo].[CHCNPORTAL_CLAIM_MASTER] ([LASTNM]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [MEMBID] ON [dbo].[CHCNPORTAL_CLAIM_MASTER] ([MEMBID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [PATID] ON [dbo].[CHCNPORTAL_CLAIM_MASTER] ([PATID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [PROVCLAIM] ON [dbo].[CHCNPORTAL_CLAIM_MASTER] ([PROVCLAIM]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [VENDOR] ON [dbo].[CHCNPORTAL_CLAIM_MASTER] ([VENDOR]) ON [PRIMARY]
GO
