CREATE TABLE [dbo].[CHCNWEB_REFPROCCODES]
(
[COMMON_ID] [int] NULL,
[PHCODE] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PROCCODE] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PROCDESC] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [WEB_PROCCODE] ON [dbo].[CHCNWEB_REFPROCCODES] ([PROCCODE]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [WEB_PROCDESC] ON [dbo].[CHCNWEB_REFPROCCODES] ([PROCDESC]) ON [PRIMARY]
GO
