CREATE TABLE [dbo].[CHCNWEB_AUTHREQ_DETAILS]
(
[REQUESTID] [int] NULL,
[DETAILNO] [smallint] NULL,
[PROCCODE] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PROCDESC] [varchar] (24) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
