CREATE TABLE [dbo].[CHCNWeb_AuthReq_Master]
(
[RequestID] [int] NOT NULL,
[AuthNoTemp] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[UrgentReq] [bit] NULL,
[CHCNReq] [bit] NULL,
[RequestDate] [datetime] NOT NULL,
[ReqName] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ReqPhone] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ReqFax] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ReqFacility] [varchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ReqProvName] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ReqProvID] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MembID] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[MembName] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[MembDOB] [datetime] NOT NULL,
[BenOPT] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[PatID] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[HPCode] [varchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[RefToProvID] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[RefToSpec] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[RefToName] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[RefToCompanyID] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[RefToCompanyName] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[SerConsult] [bit] NULL,
[SerVisit] [bit] NULL,
[SerVisitQty] [int] NULL,
[SerInPatient] [bit] NULL,
[SerOutSurgery] [bit] NULL,
[SerDME] [bit] NULL,
[SerHomeCare] [bit] NULL,
[SerHomeCareDesc] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SerClinicalDesc] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AncTreatmentDesc] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AncDOS] [datetime] NULL,
[AncFacilityID] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AncOtherServices] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Submitted] [bit] NULL
) ON [PRIMARY]
GO
