CREATE TABLE [dbo].[CHCNAUTH_RESTRICTIONS]
(
[RESTRICTIONS_ID] [int] NOT NULL IDENTITY(1, 1),
[SVCCODE] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[HEALTHPLAN] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[COVERAGE] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PROVID] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PLACESVC] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[REST_DETERM] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EFFECTIVE_DATE] [datetime] NULL,
[TERM_DATE] [datetime] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CHCNAUTH_RESTRICTIONS] ADD CONSTRAINT [PK_CHCNAUTH_RESTRICTIONS] PRIMARY KEY CLUSTERED  ([RESTRICTIONS_ID]) ON [PRIMARY]
GO
