CREATE TABLE [dbo].[CHCNPORTAL_MEMB_HISTORY]
(
[VENDOR] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MEMB_KEYID] [uniqueidentifier] NOT NULL,
[MEMBID] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[PCPFROMDT] [datetime] NOT NULL,
[PCPTHRUDT] [datetime] NULL,
[PCP] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[COMPANY_ID] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OPTNAME] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [MEMB_KEYID] ON [dbo].[CHCNPORTAL_MEMB_HISTORY] ([MEMB_KEYID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [MEMBID] ON [dbo].[CHCNPORTAL_MEMB_HISTORY] ([MEMBID]) ON [PRIMARY]
GO
